// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _operator_add_assign_float_HH_
#define _operator_add_assign_float_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "matmul_fadd_32ns_cud.h"

namespace ap_rtl {

struct operator_add_assign_float : public sc_module {
    // Port declarations 9
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<32> > complex_float_M_real_read;
    sc_in< sc_lv<32> > complex_float_M_imag_read;
    sc_in< sc_lv<32> > p_z_M_real_read;
    sc_in< sc_lv<32> > p_z_M_imag_read;
    sc_out< sc_lv<32> > ap_return_0;
    sc_out< sc_lv<32> > ap_return_1;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    operator_add_assign_float(sc_module_name name);
    SC_HAS_PROCESS(operator_add_assign_float);

    ~operator_add_assign_float();

    sc_trace_file* mVcdFile;

    matmul_fadd_32ns_cud<1,4,32,32,32>* matmul_fadd_32ns_cud_U14;
    matmul_fadd_32ns_cud<1,4,32,32,32>* matmul_fadd_32ns_cud_U15;
    sc_signal< bool > ap_block_state1_pp0_stage0_iter0;
    sc_signal< bool > ap_block_state2_pp0_stage0_iter1;
    sc_signal< bool > ap_block_state3_pp0_stage0_iter2;
    sc_signal< bool > ap_block_state4_pp0_stage0_iter3;
    sc_signal< bool > ap_block_pp0_stage0_11001;
    sc_signal< bool > ap_block_pp0_stage0;
    sc_signal< sc_lv<32> > grp_fu_36_p2;
    sc_signal< sc_lv<32> > grp_fu_42_p2;
    sc_signal< sc_logic > grp_fu_36_ce;
    sc_signal< sc_logic > grp_fu_42_ce;
    sc_signal< sc_logic > ap_ce_reg;
    sc_signal< sc_lv<32> > complex_float_M_real_read_int_reg;
    sc_signal< sc_lv<32> > complex_float_M_imag_read_int_reg;
    sc_signal< sc_lv<32> > p_z_M_real_read_int_reg;
    sc_signal< sc_lv<32> > p_z_M_imag_read_int_reg;
    sc_signal< sc_lv<32> > ap_return_0_int_reg;
    sc_signal< sc_lv<32> > ap_return_1_int_reg;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    static const bool ap_const_boolean_0;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_block_pp0_stage0();
    void thread_ap_block_pp0_stage0_11001();
    void thread_ap_block_state1_pp0_stage0_iter0();
    void thread_ap_block_state2_pp0_stage0_iter1();
    void thread_ap_block_state3_pp0_stage0_iter2();
    void thread_ap_block_state4_pp0_stage0_iter3();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_grp_fu_36_ce();
    void thread_grp_fu_42_ce();
};

}

using namespace ap_rtl;

#endif
