// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matmul,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu28dr-ffvg1517-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.419000,HLS_SYN_LAT=703,HLS_SYN_TPT=none,HLS_SYN_MEM=32,HLS_SYN_DSP=160,HLS_SYN_FF=23344,HLS_SYN_LUT=16046,HLS_VERSION=2019_2}" *)

module matmul (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_state2 = 8'd2;
parameter    ap_ST_fsm_state3 = 8'd4;
parameter    ap_ST_fsm_state4 = 8'd8;
parameter    ap_ST_fsm_state5 = 8'd16;
parameter    ap_ST_fsm_state6 = 8'd32;
parameter    ap_ST_fsm_pp0_stage0 = 8'd64;
parameter    ap_ST_fsm_state10 = 8'd128;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [7:0] in_stream_TKEEP;
input  [7:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [63:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [7:0] out_stream_TKEEP;
output  [7:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg in_stream_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [31:0] mulOut_M_real_0_0;
reg   [31:0] mulOut_M_real_0_1;
reg   [31:0] mulOut_M_real_0_2;
reg   [31:0] mulOut_M_real_0_3;
reg   [31:0] mulOut_M_real_1_0;
reg   [31:0] mulOut_M_real_1_1;
reg   [31:0] mulOut_M_real_1_2;
reg   [31:0] mulOut_M_real_1_3;
reg   [31:0] mulOut_M_real_2_0;
reg   [31:0] mulOut_M_real_2_1;
reg   [31:0] mulOut_M_real_2_2;
reg   [31:0] mulOut_M_real_2_3;
reg   [31:0] mulOut_M_real_3_0;
reg   [31:0] mulOut_M_real_3_1;
reg   [31:0] mulOut_M_real_3_2;
reg   [31:0] mulOut_M_real_3_3;
reg   [31:0] mulOut_M_imag_0_0;
reg   [31:0] mulOut_M_imag_0_1;
reg   [31:0] mulOut_M_imag_0_2;
reg   [31:0] mulOut_M_imag_0_3;
reg   [31:0] mulOut_M_imag_1_0;
reg   [31:0] mulOut_M_imag_1_1;
reg   [31:0] mulOut_M_imag_1_2;
reg   [31:0] mulOut_M_imag_1_3;
reg   [31:0] mulOut_M_imag_2_0;
reg   [31:0] mulOut_M_imag_2_1;
reg   [31:0] mulOut_M_imag_2_2;
reg   [31:0] mulOut_M_imag_2_3;
reg   [31:0] mulOut_M_imag_3_0;
reg   [31:0] mulOut_M_imag_3_1;
reg   [31:0] mulOut_M_imag_3_2;
reg   [31:0] mulOut_M_imag_3_3;
reg   [5:0] A_M_real_0_address0;
reg    A_M_real_0_ce0;
reg    A_M_real_0_we0;
wire   [31:0] A_M_real_0_q0;
reg    A_M_real_0_ce1;
wire   [31:0] A_M_real_0_q1;
reg   [5:0] A_M_real_1_address0;
reg    A_M_real_1_ce0;
reg    A_M_real_1_we0;
wire   [31:0] A_M_real_1_q0;
reg    A_M_real_1_ce1;
wire   [31:0] A_M_real_1_q1;
reg   [5:0] A_M_real_2_address0;
reg    A_M_real_2_ce0;
reg    A_M_real_2_we0;
wire   [31:0] A_M_real_2_q0;
reg    A_M_real_2_ce1;
wire   [31:0] A_M_real_2_q1;
reg   [5:0] A_M_real_3_address0;
reg    A_M_real_3_ce0;
reg    A_M_real_3_we0;
wire   [31:0] A_M_real_3_q0;
reg    A_M_real_3_ce1;
wire   [31:0] A_M_real_3_q1;
reg   [5:0] A_M_imag_0_address0;
reg    A_M_imag_0_ce0;
reg    A_M_imag_0_we0;
wire   [31:0] A_M_imag_0_q0;
reg    A_M_imag_0_ce1;
wire   [31:0] A_M_imag_0_q1;
reg   [5:0] A_M_imag_1_address0;
reg    A_M_imag_1_ce0;
reg    A_M_imag_1_we0;
wire   [31:0] A_M_imag_1_q0;
reg    A_M_imag_1_ce1;
wire   [31:0] A_M_imag_1_q1;
reg   [5:0] A_M_imag_2_address0;
reg    A_M_imag_2_ce0;
reg    A_M_imag_2_we0;
wire   [31:0] A_M_imag_2_q0;
reg    A_M_imag_2_ce1;
wire   [31:0] A_M_imag_2_q1;
reg   [5:0] A_M_imag_3_address0;
reg    A_M_imag_3_ce0;
reg    A_M_imag_3_we0;
wire   [31:0] A_M_imag_3_q0;
reg    A_M_imag_3_ce1;
wire   [31:0] A_M_imag_3_q1;
reg   [5:0] B_M_real_0_address0;
reg    B_M_real_0_ce0;
reg    B_M_real_0_we0;
wire   [31:0] B_M_real_0_q0;
reg    B_M_real_0_ce1;
wire   [31:0] B_M_real_0_q1;
reg   [5:0] B_M_real_1_address0;
reg    B_M_real_1_ce0;
reg    B_M_real_1_we0;
wire   [31:0] B_M_real_1_q0;
reg    B_M_real_1_ce1;
wire   [31:0] B_M_real_1_q1;
reg   [5:0] B_M_real_2_address0;
reg    B_M_real_2_ce0;
reg    B_M_real_2_we0;
wire   [31:0] B_M_real_2_q0;
reg    B_M_real_2_ce1;
wire   [31:0] B_M_real_2_q1;
reg   [5:0] B_M_real_3_address0;
reg    B_M_real_3_ce0;
reg    B_M_real_3_we0;
wire   [31:0] B_M_real_3_q0;
reg    B_M_real_3_ce1;
wire   [31:0] B_M_real_3_q1;
reg   [5:0] B_M_imag_0_address0;
reg    B_M_imag_0_ce0;
reg    B_M_imag_0_we0;
wire   [31:0] B_M_imag_0_q0;
reg    B_M_imag_0_ce1;
wire   [31:0] B_M_imag_0_q1;
reg   [5:0] B_M_imag_1_address0;
reg    B_M_imag_1_ce0;
reg    B_M_imag_1_we0;
wire   [31:0] B_M_imag_1_q0;
reg    B_M_imag_1_ce1;
wire   [31:0] B_M_imag_1_q1;
reg   [5:0] B_M_imag_2_address0;
reg    B_M_imag_2_ce0;
reg    B_M_imag_2_we0;
wire   [31:0] B_M_imag_2_q0;
reg    B_M_imag_2_ce1;
wire   [31:0] B_M_imag_2_q1;
reg   [5:0] B_M_imag_3_address0;
reg    B_M_imag_3_ce0;
reg    B_M_imag_3_we0;
wire   [31:0] B_M_imag_3_q0;
reg    B_M_imag_3_ce1;
wire   [31:0] B_M_imag_3_q1;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln35_fu_600_p2;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln47_fu_864_p2;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln62_reg_1686;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln62_reg_1686_pp0_iter1_reg;
reg   [4:0] i_2_reg_495;
wire   [4:0] i_fu_594_p2;
reg   [4:0] i_reg_1325;
wire    ap_CS_fsm_state2;
wire   [4:0] j_fu_606_p2;
reg    ap_block_state3;
wire   [4:0] i_4_fu_672_p2;
reg   [4:0] i_4_reg_1344;
wire    ap_CS_fsm_state4;
wire   [1:0] trunc_ln50_fu_678_p1;
reg   [1:0] trunc_ln50_reg_1349;
wire   [0:0] icmp_ln46_fu_666_p2;
wire   [7:0] zext_ln47_fu_700_p1;
reg   [7:0] zext_ln47_reg_1353;
wire   [4:0] j_2_fu_870_p2;
reg    ap_block_state5;
reg   [31:0] mulOut_M_real_0_0_r_reg_1526;
wire    ap_CS_fsm_state6;
wire    grp_DiagMatMul_fu_506_ap_ready;
wire    grp_DiagMatMul_fu_506_ap_done;
reg   [31:0] mulOut_M_real_0_1_r_reg_1531;
reg   [31:0] mulOut_M_real_0_2_r_reg_1536;
reg   [31:0] mulOut_M_real_0_3_r_reg_1541;
reg   [31:0] mulOut_M_real_1_0_r_reg_1546;
reg   [31:0] mulOut_M_real_1_1_r_reg_1551;
reg   [31:0] mulOut_M_real_1_2_r_reg_1556;
reg   [31:0] mulOut_M_real_1_3_r_reg_1561;
reg   [31:0] mulOut_M_real_2_0_r_reg_1566;
reg   [31:0] mulOut_M_real_2_1_r_reg_1571;
reg   [31:0] mulOut_M_real_2_2_r_reg_1576;
reg   [31:0] mulOut_M_real_2_3_r_reg_1581;
reg   [31:0] mulOut_M_real_3_0_r_reg_1586;
reg   [31:0] mulOut_M_real_3_1_r_reg_1591;
reg   [31:0] mulOut_M_real_3_2_r_reg_1596;
reg   [31:0] mulOut_M_real_3_3_r_reg_1601;
reg   [31:0] mulOut_M_imag_0_0_r_reg_1606;
reg   [31:0] mulOut_M_imag_0_1_r_reg_1611;
reg   [31:0] mulOut_M_imag_0_2_r_reg_1616;
reg   [31:0] mulOut_M_imag_0_3_r_reg_1621;
reg   [31:0] mulOut_M_imag_1_0_r_reg_1626;
reg   [31:0] mulOut_M_imag_1_1_r_reg_1631;
reg   [31:0] mulOut_M_imag_1_2_r_reg_1636;
reg   [31:0] mulOut_M_imag_1_3_r_reg_1641;
reg   [31:0] mulOut_M_imag_2_0_r_reg_1646;
reg   [31:0] mulOut_M_imag_2_1_r_reg_1651;
reg   [31:0] mulOut_M_imag_2_2_r_reg_1656;
reg   [31:0] mulOut_M_imag_2_3_r_reg_1661;
reg   [31:0] mulOut_M_imag_3_0_r_reg_1666;
reg   [31:0] mulOut_M_imag_3_1_r_reg_1671;
reg   [31:0] mulOut_M_imag_3_2_r_reg_1676;
reg   [31:0] mulOut_M_imag_3_3_r_reg_1681;
wire   [0:0] icmp_ln62_fu_1237_p2;
wire    ap_block_state7_pp0_stage0_iter0;
wire    ap_block_state8_pp0_stage0_iter1;
reg    ap_block_state8_io;
wire    ap_block_state9_pp0_stage0_iter2;
reg    ap_block_state9_io;
reg    ap_block_pp0_stage0_11001;
wire   [4:0] i_3_fu_1243_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [31:0] tmp_5_fu_1257_p18;
reg   [31:0] tmp_5_reg_1695;
wire   [31:0] tmp_6_fu_1279_p18;
reg   [31:0] tmp_6_reg_1700;
wire   [0:0] valOut_last_V_fu_1301_p2;
reg   [0:0] valOut_last_V_reg_1705;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state7;
wire    grp_DiagMatMul_fu_506_ap_start;
wire    grp_DiagMatMul_fu_506_ap_idle;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_real_address0;
wire    grp_DiagMatMul_fu_506_A_M_real_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_real_address1;
wire    grp_DiagMatMul_fu_506_A_M_real_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_real1_address0;
wire    grp_DiagMatMul_fu_506_A_M_real1_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_real1_address1;
wire    grp_DiagMatMul_fu_506_A_M_real1_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_real2_address0;
wire    grp_DiagMatMul_fu_506_A_M_real2_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_real2_address1;
wire    grp_DiagMatMul_fu_506_A_M_real2_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_real3_address0;
wire    grp_DiagMatMul_fu_506_A_M_real3_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_real3_address1;
wire    grp_DiagMatMul_fu_506_A_M_real3_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_imag_address0;
wire    grp_DiagMatMul_fu_506_A_M_imag_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_imag_address1;
wire    grp_DiagMatMul_fu_506_A_M_imag_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_imag4_address0;
wire    grp_DiagMatMul_fu_506_A_M_imag4_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_imag4_address1;
wire    grp_DiagMatMul_fu_506_A_M_imag4_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_imag5_address0;
wire    grp_DiagMatMul_fu_506_A_M_imag5_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_imag5_address1;
wire    grp_DiagMatMul_fu_506_A_M_imag5_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_imag6_address0;
wire    grp_DiagMatMul_fu_506_A_M_imag6_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_A_M_imag6_address1;
wire    grp_DiagMatMul_fu_506_A_M_imag6_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_real_0_address0;
wire    grp_DiagMatMul_fu_506_B_M_real_0_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_real_0_address1;
wire    grp_DiagMatMul_fu_506_B_M_real_0_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_real_1_address0;
wire    grp_DiagMatMul_fu_506_B_M_real_1_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_real_1_address1;
wire    grp_DiagMatMul_fu_506_B_M_real_1_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_real_2_address0;
wire    grp_DiagMatMul_fu_506_B_M_real_2_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_real_2_address1;
wire    grp_DiagMatMul_fu_506_B_M_real_2_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_real_3_address0;
wire    grp_DiagMatMul_fu_506_B_M_real_3_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_real_3_address1;
wire    grp_DiagMatMul_fu_506_B_M_real_3_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_imag_0_address0;
wire    grp_DiagMatMul_fu_506_B_M_imag_0_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_imag_0_address1;
wire    grp_DiagMatMul_fu_506_B_M_imag_0_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_imag_1_address0;
wire    grp_DiagMatMul_fu_506_B_M_imag_1_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_imag_1_address1;
wire    grp_DiagMatMul_fu_506_B_M_imag_1_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_imag_2_address0;
wire    grp_DiagMatMul_fu_506_B_M_imag_2_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_imag_2_address1;
wire    grp_DiagMatMul_fu_506_B_M_imag_2_ce1;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_imag_3_address0;
wire    grp_DiagMatMul_fu_506_B_M_imag_3_ce0;
wire   [5:0] grp_DiagMatMul_fu_506_B_M_imag_3_address1;
wire    grp_DiagMatMul_fu_506_B_M_imag_3_ce1;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_0;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_1;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_2;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_3;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_4;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_5;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_6;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_7;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_8;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_9;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_10;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_11;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_12;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_13;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_14;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_15;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_16;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_17;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_18;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_19;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_20;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_21;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_22;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_23;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_24;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_25;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_26;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_27;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_28;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_29;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_30;
wire   [31:0] grp_DiagMatMul_fu_506_ap_return_31;
reg   [4:0] i_0_reg_450;
reg   [4:0] j_0_reg_462;
wire   [0:0] icmp_ln34_fu_588_p2;
reg   [4:0] i_1_reg_473;
reg   [4:0] j_1_reg_484;
reg    grp_DiagMatMul_fu_506_ap_start_reg;
wire   [63:0] zext_ln38_fu_634_p1;
wire   [63:0] zext_ln50_1_fu_885_p1;
wire    ap_block_pp0_stage0_01001;
wire   [2:0] trunc_ln38_1_fu_612_p4;
wire   [31:0] bitcast_ln38_fu_646_p1;
wire   [31:0] bitcast_ln41_fu_658_p1;
wire   [31:0] bitcast_ln50_fu_897_p1;
wire   [31:0] bitcast_ln53_fu_909_p1;
wire   [1:0] trunc_ln38_fu_622_p1;
wire   [6:0] tmp_7_fu_626_p3;
wire   [31:0] grp_fu_578_p4;
wire   [31:0] trunc_ln681_fu_654_p1;
wire   [2:0] lshr_ln_fu_682_p4;
wire   [6:0] tmp_3_fu_692_p3;
wire   [7:0] zext_ln50_fu_876_p1;
wire   [7:0] add_ln50_fu_880_p2;
wire   [31:0] trunc_ln681_1_fu_905_p1;
wire   [3:0] trunc_ln64_fu_1249_p1;
wire   [4:0] zext_ln64_fu_1253_p1;
wire   [31:0] bitcast_ln64_fu_1307_p1;
wire   [31:0] bitcast_ln67_fu_1310_p1;
wire    ap_CS_fsm_state10;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [63:0] in_stream_TDATA_int;
wire    in_stream_TVALID_int;
reg    in_stream_TREADY_int;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [7:0] in_stream_TKEEP_int;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [7:0] in_stream_TSTRB_int;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire   [63:0] out_stream_TDATA_int;
reg    out_stream_TVALID_int;
wire    out_stream_TREADY_int;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 mulOut_M_real_0_0 = 32'd0;
#0 mulOut_M_real_0_1 = 32'd0;
#0 mulOut_M_real_0_2 = 32'd0;
#0 mulOut_M_real_0_3 = 32'd0;
#0 mulOut_M_real_1_0 = 32'd0;
#0 mulOut_M_real_1_1 = 32'd0;
#0 mulOut_M_real_1_2 = 32'd0;
#0 mulOut_M_real_1_3 = 32'd0;
#0 mulOut_M_real_2_0 = 32'd0;
#0 mulOut_M_real_2_1 = 32'd0;
#0 mulOut_M_real_2_2 = 32'd0;
#0 mulOut_M_real_2_3 = 32'd0;
#0 mulOut_M_real_3_0 = 32'd0;
#0 mulOut_M_real_3_1 = 32'd0;
#0 mulOut_M_real_3_2 = 32'd0;
#0 mulOut_M_real_3_3 = 32'd0;
#0 mulOut_M_imag_0_0 = 32'd0;
#0 mulOut_M_imag_0_1 = 32'd0;
#0 mulOut_M_imag_0_2 = 32'd0;
#0 mulOut_M_imag_0_3 = 32'd0;
#0 mulOut_M_imag_1_0 = 32'd0;
#0 mulOut_M_imag_1_1 = 32'd0;
#0 mulOut_M_imag_1_2 = 32'd0;
#0 mulOut_M_imag_1_3 = 32'd0;
#0 mulOut_M_imag_2_0 = 32'd0;
#0 mulOut_M_imag_2_1 = 32'd0;
#0 mulOut_M_imag_2_2 = 32'd0;
#0 mulOut_M_imag_2_3 = 32'd0;
#0 mulOut_M_imag_3_0 = 32'd0;
#0 mulOut_M_imag_3_1 = 32'd0;
#0 mulOut_M_imag_3_2 = 32'd0;
#0 mulOut_M_imag_3_3 = 32'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_DiagMatMul_fu_506_ap_start_reg = 1'b0;
end

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_M_real_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_M_real_0_address0),
    .ce0(A_M_real_0_ce0),
    .we0(A_M_real_0_we0),
    .d0(bitcast_ln38_fu_646_p1),
    .q0(A_M_real_0_q0),
    .address1(grp_DiagMatMul_fu_506_A_M_real_address1),
    .ce1(A_M_real_0_ce1),
    .q1(A_M_real_0_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_M_real_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_M_real_1_address0),
    .ce0(A_M_real_1_ce0),
    .we0(A_M_real_1_we0),
    .d0(bitcast_ln38_fu_646_p1),
    .q0(A_M_real_1_q0),
    .address1(grp_DiagMatMul_fu_506_A_M_real1_address1),
    .ce1(A_M_real_1_ce1),
    .q1(A_M_real_1_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_M_real_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_M_real_2_address0),
    .ce0(A_M_real_2_ce0),
    .we0(A_M_real_2_we0),
    .d0(bitcast_ln38_fu_646_p1),
    .q0(A_M_real_2_q0),
    .address1(grp_DiagMatMul_fu_506_A_M_real2_address1),
    .ce1(A_M_real_2_ce1),
    .q1(A_M_real_2_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_M_real_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_M_real_3_address0),
    .ce0(A_M_real_3_ce0),
    .we0(A_M_real_3_we0),
    .d0(bitcast_ln38_fu_646_p1),
    .q0(A_M_real_3_q0),
    .address1(grp_DiagMatMul_fu_506_A_M_real3_address1),
    .ce1(A_M_real_3_ce1),
    .q1(A_M_real_3_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_M_imag_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_M_imag_0_address0),
    .ce0(A_M_imag_0_ce0),
    .we0(A_M_imag_0_we0),
    .d0(bitcast_ln41_fu_658_p1),
    .q0(A_M_imag_0_q0),
    .address1(grp_DiagMatMul_fu_506_A_M_imag_address1),
    .ce1(A_M_imag_0_ce1),
    .q1(A_M_imag_0_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_M_imag_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_M_imag_1_address0),
    .ce0(A_M_imag_1_ce0),
    .we0(A_M_imag_1_we0),
    .d0(bitcast_ln41_fu_658_p1),
    .q0(A_M_imag_1_q0),
    .address1(grp_DiagMatMul_fu_506_A_M_imag4_address1),
    .ce1(A_M_imag_1_ce1),
    .q1(A_M_imag_1_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_M_imag_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_M_imag_2_address0),
    .ce0(A_M_imag_2_ce0),
    .we0(A_M_imag_2_we0),
    .d0(bitcast_ln41_fu_658_p1),
    .q0(A_M_imag_2_q0),
    .address1(grp_DiagMatMul_fu_506_A_M_imag5_address1),
    .ce1(A_M_imag_2_ce1),
    .q1(A_M_imag_2_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
A_M_imag_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(A_M_imag_3_address0),
    .ce0(A_M_imag_3_ce0),
    .we0(A_M_imag_3_we0),
    .d0(bitcast_ln41_fu_658_p1),
    .q0(A_M_imag_3_q0),
    .address1(grp_DiagMatMul_fu_506_A_M_imag6_address1),
    .ce1(A_M_imag_3_ce1),
    .q1(A_M_imag_3_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_M_real_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_M_real_0_address0),
    .ce0(B_M_real_0_ce0),
    .we0(B_M_real_0_we0),
    .d0(bitcast_ln50_fu_897_p1),
    .q0(B_M_real_0_q0),
    .address1(grp_DiagMatMul_fu_506_B_M_real_0_address1),
    .ce1(B_M_real_0_ce1),
    .q1(B_M_real_0_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_M_real_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_M_real_1_address0),
    .ce0(B_M_real_1_ce0),
    .we0(B_M_real_1_we0),
    .d0(bitcast_ln50_fu_897_p1),
    .q0(B_M_real_1_q0),
    .address1(grp_DiagMatMul_fu_506_B_M_real_1_address1),
    .ce1(B_M_real_1_ce1),
    .q1(B_M_real_1_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_M_real_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_M_real_2_address0),
    .ce0(B_M_real_2_ce0),
    .we0(B_M_real_2_we0),
    .d0(bitcast_ln50_fu_897_p1),
    .q0(B_M_real_2_q0),
    .address1(grp_DiagMatMul_fu_506_B_M_real_2_address1),
    .ce1(B_M_real_2_ce1),
    .q1(B_M_real_2_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_M_real_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_M_real_3_address0),
    .ce0(B_M_real_3_ce0),
    .we0(B_M_real_3_we0),
    .d0(bitcast_ln50_fu_897_p1),
    .q0(B_M_real_3_q0),
    .address1(grp_DiagMatMul_fu_506_B_M_real_3_address1),
    .ce1(B_M_real_3_ce1),
    .q1(B_M_real_3_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_M_imag_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_M_imag_0_address0),
    .ce0(B_M_imag_0_ce0),
    .we0(B_M_imag_0_we0),
    .d0(bitcast_ln53_fu_909_p1),
    .q0(B_M_imag_0_q0),
    .address1(grp_DiagMatMul_fu_506_B_M_imag_0_address1),
    .ce1(B_M_imag_0_ce1),
    .q1(B_M_imag_0_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_M_imag_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_M_imag_1_address0),
    .ce0(B_M_imag_1_ce0),
    .we0(B_M_imag_1_we0),
    .d0(bitcast_ln53_fu_909_p1),
    .q0(B_M_imag_1_q0),
    .address1(grp_DiagMatMul_fu_506_B_M_imag_1_address1),
    .ce1(B_M_imag_1_ce1),
    .q1(B_M_imag_1_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_M_imag_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_M_imag_2_address0),
    .ce0(B_M_imag_2_ce0),
    .we0(B_M_imag_2_we0),
    .d0(bitcast_ln53_fu_909_p1),
    .q0(B_M_imag_2_q0),
    .address1(grp_DiagMatMul_fu_506_B_M_imag_2_address1),
    .ce1(B_M_imag_2_ce1),
    .q1(B_M_imag_2_q1)
);

matmul_A_M_real_0 #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
B_M_imag_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(B_M_imag_3_address0),
    .ce0(B_M_imag_3_ce0),
    .we0(B_M_imag_3_we0),
    .d0(bitcast_ln53_fu_909_p1),
    .q0(B_M_imag_3_q0),
    .address1(grp_DiagMatMul_fu_506_B_M_imag_3_address1),
    .ce1(B_M_imag_3_ce1),
    .q1(B_M_imag_3_q1)
);

matmul_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
matmul_control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

DiagMatMul grp_DiagMatMul_fu_506(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_DiagMatMul_fu_506_ap_start),
    .ap_done(grp_DiagMatMul_fu_506_ap_done),
    .ap_idle(grp_DiagMatMul_fu_506_ap_idle),
    .ap_ready(grp_DiagMatMul_fu_506_ap_ready),
    .A_M_real_address0(grp_DiagMatMul_fu_506_A_M_real_address0),
    .A_M_real_ce0(grp_DiagMatMul_fu_506_A_M_real_ce0),
    .A_M_real_q0(A_M_real_0_q0),
    .A_M_real_address1(grp_DiagMatMul_fu_506_A_M_real_address1),
    .A_M_real_ce1(grp_DiagMatMul_fu_506_A_M_real_ce1),
    .A_M_real_q1(A_M_real_0_q1),
    .A_M_real1_address0(grp_DiagMatMul_fu_506_A_M_real1_address0),
    .A_M_real1_ce0(grp_DiagMatMul_fu_506_A_M_real1_ce0),
    .A_M_real1_q0(A_M_real_1_q0),
    .A_M_real1_address1(grp_DiagMatMul_fu_506_A_M_real1_address1),
    .A_M_real1_ce1(grp_DiagMatMul_fu_506_A_M_real1_ce1),
    .A_M_real1_q1(A_M_real_1_q1),
    .A_M_real2_address0(grp_DiagMatMul_fu_506_A_M_real2_address0),
    .A_M_real2_ce0(grp_DiagMatMul_fu_506_A_M_real2_ce0),
    .A_M_real2_q0(A_M_real_2_q0),
    .A_M_real2_address1(grp_DiagMatMul_fu_506_A_M_real2_address1),
    .A_M_real2_ce1(grp_DiagMatMul_fu_506_A_M_real2_ce1),
    .A_M_real2_q1(A_M_real_2_q1),
    .A_M_real3_address0(grp_DiagMatMul_fu_506_A_M_real3_address0),
    .A_M_real3_ce0(grp_DiagMatMul_fu_506_A_M_real3_ce0),
    .A_M_real3_q0(A_M_real_3_q0),
    .A_M_real3_address1(grp_DiagMatMul_fu_506_A_M_real3_address1),
    .A_M_real3_ce1(grp_DiagMatMul_fu_506_A_M_real3_ce1),
    .A_M_real3_q1(A_M_real_3_q1),
    .A_M_imag_address0(grp_DiagMatMul_fu_506_A_M_imag_address0),
    .A_M_imag_ce0(grp_DiagMatMul_fu_506_A_M_imag_ce0),
    .A_M_imag_q0(A_M_imag_0_q0),
    .A_M_imag_address1(grp_DiagMatMul_fu_506_A_M_imag_address1),
    .A_M_imag_ce1(grp_DiagMatMul_fu_506_A_M_imag_ce1),
    .A_M_imag_q1(A_M_imag_0_q1),
    .A_M_imag4_address0(grp_DiagMatMul_fu_506_A_M_imag4_address0),
    .A_M_imag4_ce0(grp_DiagMatMul_fu_506_A_M_imag4_ce0),
    .A_M_imag4_q0(A_M_imag_1_q0),
    .A_M_imag4_address1(grp_DiagMatMul_fu_506_A_M_imag4_address1),
    .A_M_imag4_ce1(grp_DiagMatMul_fu_506_A_M_imag4_ce1),
    .A_M_imag4_q1(A_M_imag_1_q1),
    .A_M_imag5_address0(grp_DiagMatMul_fu_506_A_M_imag5_address0),
    .A_M_imag5_ce0(grp_DiagMatMul_fu_506_A_M_imag5_ce0),
    .A_M_imag5_q0(A_M_imag_2_q0),
    .A_M_imag5_address1(grp_DiagMatMul_fu_506_A_M_imag5_address1),
    .A_M_imag5_ce1(grp_DiagMatMul_fu_506_A_M_imag5_ce1),
    .A_M_imag5_q1(A_M_imag_2_q1),
    .A_M_imag6_address0(grp_DiagMatMul_fu_506_A_M_imag6_address0),
    .A_M_imag6_ce0(grp_DiagMatMul_fu_506_A_M_imag6_ce0),
    .A_M_imag6_q0(A_M_imag_3_q0),
    .A_M_imag6_address1(grp_DiagMatMul_fu_506_A_M_imag6_address1),
    .A_M_imag6_ce1(grp_DiagMatMul_fu_506_A_M_imag6_ce1),
    .A_M_imag6_q1(A_M_imag_3_q1),
    .B_M_real_0_address0(grp_DiagMatMul_fu_506_B_M_real_0_address0),
    .B_M_real_0_ce0(grp_DiagMatMul_fu_506_B_M_real_0_ce0),
    .B_M_real_0_q0(B_M_real_0_q0),
    .B_M_real_0_address1(grp_DiagMatMul_fu_506_B_M_real_0_address1),
    .B_M_real_0_ce1(grp_DiagMatMul_fu_506_B_M_real_0_ce1),
    .B_M_real_0_q1(B_M_real_0_q1),
    .B_M_real_1_address0(grp_DiagMatMul_fu_506_B_M_real_1_address0),
    .B_M_real_1_ce0(grp_DiagMatMul_fu_506_B_M_real_1_ce0),
    .B_M_real_1_q0(B_M_real_1_q0),
    .B_M_real_1_address1(grp_DiagMatMul_fu_506_B_M_real_1_address1),
    .B_M_real_1_ce1(grp_DiagMatMul_fu_506_B_M_real_1_ce1),
    .B_M_real_1_q1(B_M_real_1_q1),
    .B_M_real_2_address0(grp_DiagMatMul_fu_506_B_M_real_2_address0),
    .B_M_real_2_ce0(grp_DiagMatMul_fu_506_B_M_real_2_ce0),
    .B_M_real_2_q0(B_M_real_2_q0),
    .B_M_real_2_address1(grp_DiagMatMul_fu_506_B_M_real_2_address1),
    .B_M_real_2_ce1(grp_DiagMatMul_fu_506_B_M_real_2_ce1),
    .B_M_real_2_q1(B_M_real_2_q1),
    .B_M_real_3_address0(grp_DiagMatMul_fu_506_B_M_real_3_address0),
    .B_M_real_3_ce0(grp_DiagMatMul_fu_506_B_M_real_3_ce0),
    .B_M_real_3_q0(B_M_real_3_q0),
    .B_M_real_3_address1(grp_DiagMatMul_fu_506_B_M_real_3_address1),
    .B_M_real_3_ce1(grp_DiagMatMul_fu_506_B_M_real_3_ce1),
    .B_M_real_3_q1(B_M_real_3_q1),
    .B_M_imag_0_address0(grp_DiagMatMul_fu_506_B_M_imag_0_address0),
    .B_M_imag_0_ce0(grp_DiagMatMul_fu_506_B_M_imag_0_ce0),
    .B_M_imag_0_q0(B_M_imag_0_q0),
    .B_M_imag_0_address1(grp_DiagMatMul_fu_506_B_M_imag_0_address1),
    .B_M_imag_0_ce1(grp_DiagMatMul_fu_506_B_M_imag_0_ce1),
    .B_M_imag_0_q1(B_M_imag_0_q1),
    .B_M_imag_1_address0(grp_DiagMatMul_fu_506_B_M_imag_1_address0),
    .B_M_imag_1_ce0(grp_DiagMatMul_fu_506_B_M_imag_1_ce0),
    .B_M_imag_1_q0(B_M_imag_1_q0),
    .B_M_imag_1_address1(grp_DiagMatMul_fu_506_B_M_imag_1_address1),
    .B_M_imag_1_ce1(grp_DiagMatMul_fu_506_B_M_imag_1_ce1),
    .B_M_imag_1_q1(B_M_imag_1_q1),
    .B_M_imag_2_address0(grp_DiagMatMul_fu_506_B_M_imag_2_address0),
    .B_M_imag_2_ce0(grp_DiagMatMul_fu_506_B_M_imag_2_ce0),
    .B_M_imag_2_q0(B_M_imag_2_q0),
    .B_M_imag_2_address1(grp_DiagMatMul_fu_506_B_M_imag_2_address1),
    .B_M_imag_2_ce1(grp_DiagMatMul_fu_506_B_M_imag_2_ce1),
    .B_M_imag_2_q1(B_M_imag_2_q1),
    .B_M_imag_3_address0(grp_DiagMatMul_fu_506_B_M_imag_3_address0),
    .B_M_imag_3_ce0(grp_DiagMatMul_fu_506_B_M_imag_3_ce0),
    .B_M_imag_3_q0(B_M_imag_3_q0),
    .B_M_imag_3_address1(grp_DiagMatMul_fu_506_B_M_imag_3_address1),
    .B_M_imag_3_ce1(grp_DiagMatMul_fu_506_B_M_imag_3_ce1),
    .B_M_imag_3_q1(B_M_imag_3_q1),
    .C_M_real_0_0_read(mulOut_M_real_0_0),
    .C_M_real_0_1_read(mulOut_M_real_0_1),
    .C_M_real_0_2_read(mulOut_M_real_0_2),
    .C_M_real_0_3_read(mulOut_M_real_0_3),
    .C_M_real_1_0_read(mulOut_M_real_1_0),
    .C_M_real_1_1_read(mulOut_M_real_1_1),
    .C_M_real_1_2_read(mulOut_M_real_1_2),
    .C_M_real_1_3_read(mulOut_M_real_1_3),
    .C_M_real_2_0_read(mulOut_M_real_2_0),
    .C_M_real_2_1_read(mulOut_M_real_2_1),
    .C_M_real_2_2_read(mulOut_M_real_2_2),
    .C_M_real_2_3_read(mulOut_M_real_2_3),
    .C_M_real_3_0_read(mulOut_M_real_3_0),
    .C_M_real_3_1_read(mulOut_M_real_3_1),
    .C_M_real_3_2_read(mulOut_M_real_3_2),
    .C_M_real_3_3_read(mulOut_M_real_3_3),
    .C_M_imag_0_0_read(mulOut_M_imag_0_0),
    .C_M_imag_0_1_read(mulOut_M_imag_0_1),
    .C_M_imag_0_2_read(mulOut_M_imag_0_2),
    .C_M_imag_0_3_read(mulOut_M_imag_0_3),
    .C_M_imag_1_0_read(mulOut_M_imag_1_0),
    .C_M_imag_1_1_read(mulOut_M_imag_1_1),
    .C_M_imag_1_2_read(mulOut_M_imag_1_2),
    .C_M_imag_1_3_read(mulOut_M_imag_1_3),
    .C_M_imag_2_0_read(mulOut_M_imag_2_0),
    .C_M_imag_2_1_read(mulOut_M_imag_2_1),
    .C_M_imag_2_2_read(mulOut_M_imag_2_2),
    .C_M_imag_2_3_read(mulOut_M_imag_2_3),
    .C_M_imag_3_0_read(mulOut_M_imag_3_0),
    .C_M_imag_3_1_read(mulOut_M_imag_3_1),
    .C_M_imag_3_2_read(mulOut_M_imag_3_2),
    .C_M_imag_3_3_read(mulOut_M_imag_3_3),
    .ap_return_0(grp_DiagMatMul_fu_506_ap_return_0),
    .ap_return_1(grp_DiagMatMul_fu_506_ap_return_1),
    .ap_return_2(grp_DiagMatMul_fu_506_ap_return_2),
    .ap_return_3(grp_DiagMatMul_fu_506_ap_return_3),
    .ap_return_4(grp_DiagMatMul_fu_506_ap_return_4),
    .ap_return_5(grp_DiagMatMul_fu_506_ap_return_5),
    .ap_return_6(grp_DiagMatMul_fu_506_ap_return_6),
    .ap_return_7(grp_DiagMatMul_fu_506_ap_return_7),
    .ap_return_8(grp_DiagMatMul_fu_506_ap_return_8),
    .ap_return_9(grp_DiagMatMul_fu_506_ap_return_9),
    .ap_return_10(grp_DiagMatMul_fu_506_ap_return_10),
    .ap_return_11(grp_DiagMatMul_fu_506_ap_return_11),
    .ap_return_12(grp_DiagMatMul_fu_506_ap_return_12),
    .ap_return_13(grp_DiagMatMul_fu_506_ap_return_13),
    .ap_return_14(grp_DiagMatMul_fu_506_ap_return_14),
    .ap_return_15(grp_DiagMatMul_fu_506_ap_return_15),
    .ap_return_16(grp_DiagMatMul_fu_506_ap_return_16),
    .ap_return_17(grp_DiagMatMul_fu_506_ap_return_17),
    .ap_return_18(grp_DiagMatMul_fu_506_ap_return_18),
    .ap_return_19(grp_DiagMatMul_fu_506_ap_return_19),
    .ap_return_20(grp_DiagMatMul_fu_506_ap_return_20),
    .ap_return_21(grp_DiagMatMul_fu_506_ap_return_21),
    .ap_return_22(grp_DiagMatMul_fu_506_ap_return_22),
    .ap_return_23(grp_DiagMatMul_fu_506_ap_return_23),
    .ap_return_24(grp_DiagMatMul_fu_506_ap_return_24),
    .ap_return_25(grp_DiagMatMul_fu_506_ap_return_25),
    .ap_return_26(grp_DiagMatMul_fu_506_ap_return_26),
    .ap_return_27(grp_DiagMatMul_fu_506_ap_return_27),
    .ap_return_28(grp_DiagMatMul_fu_506_ap_return_28),
    .ap_return_29(grp_DiagMatMul_fu_506_ap_return_29),
    .ap_return_30(grp_DiagMatMul_fu_506_ap_return_30),
    .ap_return_31(grp_DiagMatMul_fu_506_ap_return_31)
);

matmul_mux_165_32eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
matmul_mux_165_32eOg_U78(
    .din0(mulOut_M_real_0_0_r_reg_1526),
    .din1(mulOut_M_real_0_1_r_reg_1531),
    .din2(mulOut_M_real_0_2_r_reg_1536),
    .din3(mulOut_M_real_0_3_r_reg_1541),
    .din4(mulOut_M_real_1_0_r_reg_1546),
    .din5(mulOut_M_real_1_1_r_reg_1551),
    .din6(mulOut_M_real_1_2_r_reg_1556),
    .din7(mulOut_M_real_1_3_r_reg_1561),
    .din8(mulOut_M_real_2_0_r_reg_1566),
    .din9(mulOut_M_real_2_1_r_reg_1571),
    .din10(mulOut_M_real_2_2_r_reg_1576),
    .din11(mulOut_M_real_2_3_r_reg_1581),
    .din12(mulOut_M_real_3_0_r_reg_1586),
    .din13(mulOut_M_real_3_1_r_reg_1591),
    .din14(mulOut_M_real_3_2_r_reg_1596),
    .din15(mulOut_M_real_3_3_r_reg_1601),
    .din16(zext_ln64_fu_1253_p1),
    .dout(tmp_5_fu_1257_p18)
);

matmul_mux_165_32eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 5 ),
    .dout_WIDTH( 32 ))
matmul_mux_165_32eOg_U79(
    .din0(mulOut_M_imag_0_0_r_reg_1606),
    .din1(mulOut_M_imag_0_1_r_reg_1611),
    .din2(mulOut_M_imag_0_2_r_reg_1616),
    .din3(mulOut_M_imag_0_3_r_reg_1621),
    .din4(mulOut_M_imag_1_0_r_reg_1626),
    .din5(mulOut_M_imag_1_1_r_reg_1631),
    .din6(mulOut_M_imag_1_2_r_reg_1636),
    .din7(mulOut_M_imag_1_3_r_reg_1641),
    .din8(mulOut_M_imag_2_0_r_reg_1646),
    .din9(mulOut_M_imag_2_1_r_reg_1651),
    .din10(mulOut_M_imag_2_2_r_reg_1656),
    .din11(mulOut_M_imag_2_3_r_reg_1661),
    .din12(mulOut_M_imag_3_0_r_reg_1666),
    .din13(mulOut_M_imag_3_1_r_reg_1671),
    .din14(mulOut_M_imag_3_2_r_reg_1676),
    .din15(mulOut_M_imag_3_3_r_reg_1681),
    .din16(zext_ln64_fu_1253_p1),
    .dout(tmp_6_fu_1279_p18)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int),
    .vld_out(in_stream_TVALID_int),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int),
    .vld_in(out_stream_TVALID_int),
    .ack_in(out_stream_TREADY_int),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd15),
    .vld_in(out_stream_TVALID_int),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd255),
    .vld_in(out_stream_TVALID_int),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(valOut_last_V_reg_1705),
    .vld_in(out_stream_TVALID_int),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state7) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((grp_DiagMatMul_fu_506_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state7)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state7);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((grp_DiagMatMul_fu_506_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_DiagMatMul_fu_506_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln46_fu_666_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
            grp_DiagMatMul_fu_506_ap_start_reg <= 1'b1;
        end else if ((grp_DiagMatMul_fu_506_ap_ready == 1'b1)) begin
            grp_DiagMatMul_fu_506_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_0_reg_450 <= 5'd0;
    end else if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (icmp_ln35_fu_600_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_0_reg_450 <= i_reg_1325;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln34_fu_588_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_1_reg_473 <= 5'd0;
    end else if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (icmp_ln47_fu_864_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        i_1_reg_473 <= i_4_reg_1344;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln62_fu_1237_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_2_reg_495 <= i_3_fu_1243_p2;
    end else if (((grp_DiagMatMul_fu_506_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        i_2_reg_495 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        j_0_reg_462 <= j_fu_606_p2;
    end else if (((icmp_ln34_fu_588_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_0_reg_462 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        j_1_reg_484 <= j_2_fu_870_p2;
    end else if (((icmp_ln46_fu_666_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        j_1_reg_484 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        i_4_reg_1344 <= i_4_fu_672_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_1325 <= i_fu_594_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln62_reg_1686 <= icmp_ln62_fu_1237_p2;
        icmp_ln62_reg_1686_pp0_iter1_reg <= icmp_ln62_reg_1686;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_DiagMatMul_fu_506_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
        mulOut_M_imag_0_0 <= grp_DiagMatMul_fu_506_ap_return_16;
        mulOut_M_imag_0_0_r_reg_1606 <= grp_DiagMatMul_fu_506_ap_return_16;
        mulOut_M_imag_0_1 <= grp_DiagMatMul_fu_506_ap_return_17;
        mulOut_M_imag_0_1_r_reg_1611 <= grp_DiagMatMul_fu_506_ap_return_17;
        mulOut_M_imag_0_2 <= grp_DiagMatMul_fu_506_ap_return_18;
        mulOut_M_imag_0_2_r_reg_1616 <= grp_DiagMatMul_fu_506_ap_return_18;
        mulOut_M_imag_0_3 <= grp_DiagMatMul_fu_506_ap_return_19;
        mulOut_M_imag_0_3_r_reg_1621 <= grp_DiagMatMul_fu_506_ap_return_19;
        mulOut_M_imag_1_0 <= grp_DiagMatMul_fu_506_ap_return_20;
        mulOut_M_imag_1_0_r_reg_1626 <= grp_DiagMatMul_fu_506_ap_return_20;
        mulOut_M_imag_1_1 <= grp_DiagMatMul_fu_506_ap_return_21;
        mulOut_M_imag_1_1_r_reg_1631 <= grp_DiagMatMul_fu_506_ap_return_21;
        mulOut_M_imag_1_2 <= grp_DiagMatMul_fu_506_ap_return_22;
        mulOut_M_imag_1_2_r_reg_1636 <= grp_DiagMatMul_fu_506_ap_return_22;
        mulOut_M_imag_1_3 <= grp_DiagMatMul_fu_506_ap_return_23;
        mulOut_M_imag_1_3_r_reg_1641 <= grp_DiagMatMul_fu_506_ap_return_23;
        mulOut_M_imag_2_0 <= grp_DiagMatMul_fu_506_ap_return_24;
        mulOut_M_imag_2_0_r_reg_1646 <= grp_DiagMatMul_fu_506_ap_return_24;
        mulOut_M_imag_2_1 <= grp_DiagMatMul_fu_506_ap_return_25;
        mulOut_M_imag_2_1_r_reg_1651 <= grp_DiagMatMul_fu_506_ap_return_25;
        mulOut_M_imag_2_2 <= grp_DiagMatMul_fu_506_ap_return_26;
        mulOut_M_imag_2_2_r_reg_1656 <= grp_DiagMatMul_fu_506_ap_return_26;
        mulOut_M_imag_2_3 <= grp_DiagMatMul_fu_506_ap_return_27;
        mulOut_M_imag_2_3_r_reg_1661 <= grp_DiagMatMul_fu_506_ap_return_27;
        mulOut_M_imag_3_0 <= grp_DiagMatMul_fu_506_ap_return_28;
        mulOut_M_imag_3_0_r_reg_1666 <= grp_DiagMatMul_fu_506_ap_return_28;
        mulOut_M_imag_3_1 <= grp_DiagMatMul_fu_506_ap_return_29;
        mulOut_M_imag_3_1_r_reg_1671 <= grp_DiagMatMul_fu_506_ap_return_29;
        mulOut_M_imag_3_2 <= grp_DiagMatMul_fu_506_ap_return_30;
        mulOut_M_imag_3_2_r_reg_1676 <= grp_DiagMatMul_fu_506_ap_return_30;
        mulOut_M_imag_3_3 <= grp_DiagMatMul_fu_506_ap_return_31;
        mulOut_M_imag_3_3_r_reg_1681 <= grp_DiagMatMul_fu_506_ap_return_31;
        mulOut_M_real_0_0 <= grp_DiagMatMul_fu_506_ap_return_0;
        mulOut_M_real_0_0_r_reg_1526 <= grp_DiagMatMul_fu_506_ap_return_0;
        mulOut_M_real_0_1 <= grp_DiagMatMul_fu_506_ap_return_1;
        mulOut_M_real_0_1_r_reg_1531 <= grp_DiagMatMul_fu_506_ap_return_1;
        mulOut_M_real_0_2 <= grp_DiagMatMul_fu_506_ap_return_2;
        mulOut_M_real_0_2_r_reg_1536 <= grp_DiagMatMul_fu_506_ap_return_2;
        mulOut_M_real_0_3 <= grp_DiagMatMul_fu_506_ap_return_3;
        mulOut_M_real_0_3_r_reg_1541 <= grp_DiagMatMul_fu_506_ap_return_3;
        mulOut_M_real_1_0 <= grp_DiagMatMul_fu_506_ap_return_4;
        mulOut_M_real_1_0_r_reg_1546 <= grp_DiagMatMul_fu_506_ap_return_4;
        mulOut_M_real_1_1 <= grp_DiagMatMul_fu_506_ap_return_5;
        mulOut_M_real_1_1_r_reg_1551 <= grp_DiagMatMul_fu_506_ap_return_5;
        mulOut_M_real_1_2 <= grp_DiagMatMul_fu_506_ap_return_6;
        mulOut_M_real_1_2_r_reg_1556 <= grp_DiagMatMul_fu_506_ap_return_6;
        mulOut_M_real_1_3 <= grp_DiagMatMul_fu_506_ap_return_7;
        mulOut_M_real_1_3_r_reg_1561 <= grp_DiagMatMul_fu_506_ap_return_7;
        mulOut_M_real_2_0 <= grp_DiagMatMul_fu_506_ap_return_8;
        mulOut_M_real_2_0_r_reg_1566 <= grp_DiagMatMul_fu_506_ap_return_8;
        mulOut_M_real_2_1 <= grp_DiagMatMul_fu_506_ap_return_9;
        mulOut_M_real_2_1_r_reg_1571 <= grp_DiagMatMul_fu_506_ap_return_9;
        mulOut_M_real_2_2 <= grp_DiagMatMul_fu_506_ap_return_10;
        mulOut_M_real_2_2_r_reg_1576 <= grp_DiagMatMul_fu_506_ap_return_10;
        mulOut_M_real_2_3 <= grp_DiagMatMul_fu_506_ap_return_11;
        mulOut_M_real_2_3_r_reg_1581 <= grp_DiagMatMul_fu_506_ap_return_11;
        mulOut_M_real_3_0 <= grp_DiagMatMul_fu_506_ap_return_12;
        mulOut_M_real_3_0_r_reg_1586 <= grp_DiagMatMul_fu_506_ap_return_12;
        mulOut_M_real_3_1 <= grp_DiagMatMul_fu_506_ap_return_13;
        mulOut_M_real_3_1_r_reg_1591 <= grp_DiagMatMul_fu_506_ap_return_13;
        mulOut_M_real_3_2 <= grp_DiagMatMul_fu_506_ap_return_14;
        mulOut_M_real_3_2_r_reg_1596 <= grp_DiagMatMul_fu_506_ap_return_14;
        mulOut_M_real_3_3 <= grp_DiagMatMul_fu_506_ap_return_15;
        mulOut_M_real_3_3_r_reg_1601 <= grp_DiagMatMul_fu_506_ap_return_15;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln62_fu_1237_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_5_reg_1695 <= tmp_5_fu_1257_p18;
        tmp_6_reg_1700 <= tmp_6_fu_1279_p18;
        valOut_last_V_reg_1705 <= valOut_last_V_fu_1301_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln46_fu_666_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        trunc_ln50_reg_1349 <= trunc_ln50_fu_678_p1;
        zext_ln47_reg_1353[6 : 4] <= zext_ln47_fu_700_p1[6 : 4];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_M_imag_0_address0 = zext_ln38_fu_634_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_0_address0 = grp_DiagMatMul_fu_506_A_M_imag_address0;
    end else begin
        A_M_imag_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_imag_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_0_ce0 = grp_DiagMatMul_fu_506_A_M_imag_ce0;
    end else begin
        A_M_imag_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_0_ce1 = grp_DiagMatMul_fu_506_A_M_imag_ce1;
    end else begin
        A_M_imag_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (trunc_ln38_1_fu_612_p4 == 3'd0) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_imag_0_we0 = 1'b1;
    end else begin
        A_M_imag_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_M_imag_1_address0 = zext_ln38_fu_634_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_1_address0 = grp_DiagMatMul_fu_506_A_M_imag4_address0;
    end else begin
        A_M_imag_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_imag_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_1_ce0 = grp_DiagMatMul_fu_506_A_M_imag4_ce0;
    end else begin
        A_M_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_1_ce1 = grp_DiagMatMul_fu_506_A_M_imag4_ce1;
    end else begin
        A_M_imag_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (trunc_ln38_1_fu_612_p4 == 3'd1) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_imag_1_we0 = 1'b1;
    end else begin
        A_M_imag_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_M_imag_2_address0 = zext_ln38_fu_634_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_2_address0 = grp_DiagMatMul_fu_506_A_M_imag5_address0;
    end else begin
        A_M_imag_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_imag_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_2_ce0 = grp_DiagMatMul_fu_506_A_M_imag5_ce0;
    end else begin
        A_M_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_2_ce1 = grp_DiagMatMul_fu_506_A_M_imag5_ce1;
    end else begin
        A_M_imag_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (trunc_ln38_1_fu_612_p4 == 3'd2) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_imag_2_we0 = 1'b1;
    end else begin
        A_M_imag_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_M_imag_3_address0 = zext_ln38_fu_634_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_3_address0 = grp_DiagMatMul_fu_506_A_M_imag6_address0;
    end else begin
        A_M_imag_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_imag_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_3_ce0 = grp_DiagMatMul_fu_506_A_M_imag6_ce0;
    end else begin
        A_M_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_imag_3_ce1 = grp_DiagMatMul_fu_506_A_M_imag6_ce1;
    end else begin
        A_M_imag_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln38_1_fu_612_p4 == 3'd0) & ~(trunc_ln38_1_fu_612_p4 == 3'd1) & ~(trunc_ln38_1_fu_612_p4 == 3'd2) & ~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_imag_3_we0 = 1'b1;
    end else begin
        A_M_imag_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_M_real_0_address0 = zext_ln38_fu_634_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_0_address0 = grp_DiagMatMul_fu_506_A_M_real_address0;
    end else begin
        A_M_real_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_real_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_0_ce0 = grp_DiagMatMul_fu_506_A_M_real_ce0;
    end else begin
        A_M_real_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_0_ce1 = grp_DiagMatMul_fu_506_A_M_real_ce1;
    end else begin
        A_M_real_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (trunc_ln38_1_fu_612_p4 == 3'd0) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_real_0_we0 = 1'b1;
    end else begin
        A_M_real_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_M_real_1_address0 = zext_ln38_fu_634_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_1_address0 = grp_DiagMatMul_fu_506_A_M_real1_address0;
    end else begin
        A_M_real_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_real_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_1_ce0 = grp_DiagMatMul_fu_506_A_M_real1_ce0;
    end else begin
        A_M_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_1_ce1 = grp_DiagMatMul_fu_506_A_M_real1_ce1;
    end else begin
        A_M_real_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (trunc_ln38_1_fu_612_p4 == 3'd1) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_real_1_we0 = 1'b1;
    end else begin
        A_M_real_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_M_real_2_address0 = zext_ln38_fu_634_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_2_address0 = grp_DiagMatMul_fu_506_A_M_real2_address0;
    end else begin
        A_M_real_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_real_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_2_ce0 = grp_DiagMatMul_fu_506_A_M_real2_ce0;
    end else begin
        A_M_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_2_ce1 = grp_DiagMatMul_fu_506_A_M_real2_ce1;
    end else begin
        A_M_real_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (trunc_ln38_1_fu_612_p4 == 3'd2) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_real_2_we0 = 1'b1;
    end else begin
        A_M_real_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        A_M_real_3_address0 = zext_ln38_fu_634_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_3_address0 = grp_DiagMatMul_fu_506_A_M_real3_address0;
    end else begin
        A_M_real_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_real_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_3_ce0 = grp_DiagMatMul_fu_506_A_M_real3_ce0;
    end else begin
        A_M_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        A_M_real_3_ce1 = grp_DiagMatMul_fu_506_A_M_real3_ce1;
    end else begin
        A_M_real_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln38_1_fu_612_p4 == 3'd0) & ~(trunc_ln38_1_fu_612_p4 == 3'd1) & ~(trunc_ln38_1_fu_612_p4 == 3'd2) & ~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        A_M_real_3_we0 = 1'b1;
    end else begin
        A_M_real_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_M_imag_0_address0 = zext_ln50_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_0_address0 = grp_DiagMatMul_fu_506_B_M_imag_0_address0;
    end else begin
        B_M_imag_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_imag_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_0_ce0 = grp_DiagMatMul_fu_506_B_M_imag_0_ce0;
    end else begin
        B_M_imag_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_0_ce1 = grp_DiagMatMul_fu_506_B_M_imag_0_ce1;
    end else begin
        B_M_imag_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (trunc_ln50_reg_1349 == 2'd0) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_imag_0_we0 = 1'b1;
    end else begin
        B_M_imag_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_M_imag_1_address0 = zext_ln50_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_1_address0 = grp_DiagMatMul_fu_506_B_M_imag_1_address0;
    end else begin
        B_M_imag_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_imag_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_1_ce0 = grp_DiagMatMul_fu_506_B_M_imag_1_ce0;
    end else begin
        B_M_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_1_ce1 = grp_DiagMatMul_fu_506_B_M_imag_1_ce1;
    end else begin
        B_M_imag_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (trunc_ln50_reg_1349 == 2'd1) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_imag_1_we0 = 1'b1;
    end else begin
        B_M_imag_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_M_imag_2_address0 = zext_ln50_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_2_address0 = grp_DiagMatMul_fu_506_B_M_imag_2_address0;
    end else begin
        B_M_imag_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_imag_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_2_ce0 = grp_DiagMatMul_fu_506_B_M_imag_2_ce0;
    end else begin
        B_M_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_2_ce1 = grp_DiagMatMul_fu_506_B_M_imag_2_ce1;
    end else begin
        B_M_imag_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (trunc_ln50_reg_1349 == 2'd2) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_imag_2_we0 = 1'b1;
    end else begin
        B_M_imag_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_M_imag_3_address0 = zext_ln50_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_3_address0 = grp_DiagMatMul_fu_506_B_M_imag_3_address0;
    end else begin
        B_M_imag_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_imag_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_3_ce0 = grp_DiagMatMul_fu_506_B_M_imag_3_ce0;
    end else begin
        B_M_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_imag_3_ce1 = grp_DiagMatMul_fu_506_B_M_imag_3_ce1;
    end else begin
        B_M_imag_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (trunc_ln50_reg_1349 == 2'd3) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_imag_3_we0 = 1'b1;
    end else begin
        B_M_imag_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_M_real_0_address0 = zext_ln50_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_0_address0 = grp_DiagMatMul_fu_506_B_M_real_0_address0;
    end else begin
        B_M_real_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_real_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_0_ce0 = grp_DiagMatMul_fu_506_B_M_real_0_ce0;
    end else begin
        B_M_real_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_0_ce1 = grp_DiagMatMul_fu_506_B_M_real_0_ce1;
    end else begin
        B_M_real_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (trunc_ln50_reg_1349 == 2'd0) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_real_0_we0 = 1'b1;
    end else begin
        B_M_real_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_M_real_1_address0 = zext_ln50_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_1_address0 = grp_DiagMatMul_fu_506_B_M_real_1_address0;
    end else begin
        B_M_real_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_real_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_1_ce0 = grp_DiagMatMul_fu_506_B_M_real_1_ce0;
    end else begin
        B_M_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_1_ce1 = grp_DiagMatMul_fu_506_B_M_real_1_ce1;
    end else begin
        B_M_real_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (trunc_ln50_reg_1349 == 2'd1) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_real_1_we0 = 1'b1;
    end else begin
        B_M_real_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_M_real_2_address0 = zext_ln50_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_2_address0 = grp_DiagMatMul_fu_506_B_M_real_2_address0;
    end else begin
        B_M_real_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_real_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_2_ce0 = grp_DiagMatMul_fu_506_B_M_real_2_ce0;
    end else begin
        B_M_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_2_ce1 = grp_DiagMatMul_fu_506_B_M_real_2_ce1;
    end else begin
        B_M_real_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (trunc_ln50_reg_1349 == 2'd2) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_real_2_we0 = 1'b1;
    end else begin
        B_M_real_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        B_M_real_3_address0 = zext_ln50_1_fu_885_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_3_address0 = grp_DiagMatMul_fu_506_B_M_real_3_address0;
    end else begin
        B_M_real_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_real_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_3_ce0 = grp_DiagMatMul_fu_506_B_M_real_3_ce0;
    end else begin
        B_M_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        B_M_real_3_ce1 = grp_DiagMatMul_fu_506_B_M_real_3_ce1;
    end else begin
        B_M_real_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (trunc_ln50_reg_1349 == 2'd3) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        B_M_real_3_we0 = 1'b1;
    end else begin
        B_M_real_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln62_fu_1237_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state7 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state7 = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | ((icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((in_stream_TVALID == 1'b1) & (regslice_both_in_stream_V_data_V_U_ack_in == 1'b1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5)) | (~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        in_stream_TREADY_int = 1'b1;
    end else begin
        in_stream_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln62_reg_1686_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln62_reg_1686 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln62_reg_1686 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_TVALID_int = 1'b1;
    end else begin
        out_stream_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln34_fu_588_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (icmp_ln35_fu_600_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0)) & (icmp_ln35_fu_600_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_ln46_fu_666_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state5 : begin
            if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (icmp_ln47_fu_864_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else if ((~((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0)) & (icmp_ln47_fu_864_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((grp_DiagMatMul_fu_506_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln62_fu_1237_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln62_fu_1237_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln50_fu_880_p2 = (zext_ln50_fu_876_p1 + zext_ln47_reg_1353);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state8_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state3 = ((in_stream_TVALID_int == 1'b0) & (icmp_ln35_fu_600_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state5 = ((in_stream_TVALID_int == 1'b0) & (icmp_ln47_fu_864_p2 == 1'd0));
end

assign ap_block_state7_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state8_io = ((out_stream_TREADY_int == 1'b0) & (icmp_ln62_reg_1686 == 1'd0));
end

assign ap_block_state8_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((out_stream_TREADY_int == 1'b0) & (icmp_ln62_reg_1686_pp0_iter1_reg == 1'd0));
end

assign ap_block_state9_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln38_fu_646_p1 = grp_fu_578_p4;

assign bitcast_ln41_fu_658_p1 = trunc_ln681_fu_654_p1;

assign bitcast_ln50_fu_897_p1 = grp_fu_578_p4;

assign bitcast_ln53_fu_909_p1 = trunc_ln681_1_fu_905_p1;

assign bitcast_ln64_fu_1307_p1 = tmp_5_reg_1695;

assign bitcast_ln67_fu_1310_p1 = tmp_6_reg_1700;

assign grp_DiagMatMul_fu_506_ap_start = grp_DiagMatMul_fu_506_ap_start_reg;

assign grp_fu_578_p4 = {{in_stream_TDATA_int[63:32]}};

assign i_3_fu_1243_p2 = (i_2_reg_495 + 5'd1);

assign i_4_fu_672_p2 = (i_1_reg_473 + 5'd1);

assign i_fu_594_p2 = (i_0_reg_450 + 5'd1);

assign icmp_ln34_fu_588_p2 = ((i_0_reg_450 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln35_fu_600_p2 = ((j_0_reg_462 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_666_p2 = ((i_1_reg_473 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln47_fu_864_p2 = ((j_1_reg_484 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_1237_p2 = ((i_2_reg_495 == 5'd16) ? 1'b1 : 1'b0);

assign j_2_fu_870_p2 = (j_1_reg_484 + 5'd1);

assign j_fu_606_p2 = (j_0_reg_462 + 5'd1);

assign lshr_ln_fu_682_p4 = {{i_1_reg_473[4:2]}};

assign out_stream_TDATA_int = {{bitcast_ln64_fu_1307_p1}, {bitcast_ln67_fu_1310_p1}};

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign tmp_3_fu_692_p3 = {{lshr_ln_fu_682_p4}, {4'd0}};

assign tmp_7_fu_626_p3 = {{i_0_reg_450}, {trunc_ln38_fu_622_p1}};

assign trunc_ln38_1_fu_612_p4 = {{j_0_reg_462[4:2]}};

assign trunc_ln38_fu_622_p1 = j_0_reg_462[1:0];

assign trunc_ln50_fu_678_p1 = i_1_reg_473[1:0];

assign trunc_ln64_fu_1249_p1 = i_2_reg_495[3:0];

assign trunc_ln681_1_fu_905_p1 = in_stream_TDATA_int[31:0];

assign trunc_ln681_fu_654_p1 = in_stream_TDATA_int[31:0];

assign valOut_last_V_fu_1301_p2 = ((i_2_reg_495 == 5'd15) ? 1'b1 : 1'b0);

assign zext_ln38_fu_634_p1 = tmp_7_fu_626_p3;

assign zext_ln47_fu_700_p1 = tmp_3_fu_692_p3;

assign zext_ln50_1_fu_885_p1 = add_ln50_fu_880_p2;

assign zext_ln50_fu_876_p1 = j_1_reg_484;

assign zext_ln64_fu_1253_p1 = trunc_ln64_fu_1249_p1;

always @ (posedge ap_clk) begin
    zext_ln47_reg_1353[3:0] <= 4'b0000;
    zext_ln47_reg_1353[7] <= 1'b0;
end

endmodule //matmul
