// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="matmul,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu28dr-ffvg1517-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=8.419000,HLS_SYN_LAT=36296,HLS_SYN_TPT=none,HLS_SYN_MEM=136,HLS_SYN_DSP=160,HLS_SYN_FF=40055,HLS_SYN_LUT=21921,HLS_VERSION=2019_2}" *)

module matmul (
        ap_clk,
        ap_rst_n,
        in_stream_TDATA,
        in_stream_TVALID,
        in_stream_TREADY,
        in_stream_TKEEP,
        in_stream_TSTRB,
        in_stream_TLAST,
        out_stream_TDATA,
        out_stream_TVALID,
        out_stream_TREADY,
        out_stream_TKEEP,
        out_stream_TSTRB,
        out_stream_TLAST,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_pp0_stage0 = 9'd128;
parameter    ap_ST_fsm_state11 = 9'd256;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 4;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [63:0] in_stream_TDATA;
input   in_stream_TVALID;
output   in_stream_TREADY;
input  [7:0] in_stream_TKEEP;
input  [7:0] in_stream_TSTRB;
input  [0:0] in_stream_TLAST;
output  [63:0] out_stream_TDATA;
output   out_stream_TVALID;
input   out_stream_TREADY;
output  [7:0] out_stream_TKEEP;
output  [7:0] out_stream_TSTRB;
output  [0:0] out_stream_TLAST;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

reg in_stream_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
reg   [11:0] rxmat_M_real_0_address0;
reg    rxmat_M_real_0_ce0;
reg    rxmat_M_real_0_we0;
wire   [31:0] rxmat_M_real_0_q0;
reg    rxmat_M_real_0_ce1;
wire   [31:0] rxmat_M_real_0_q1;
reg   [11:0] rxmat_M_real_1_address0;
reg    rxmat_M_real_1_ce0;
reg    rxmat_M_real_1_we0;
wire   [31:0] rxmat_M_real_1_q0;
reg    rxmat_M_real_1_ce1;
wire   [31:0] rxmat_M_real_1_q1;
reg   [11:0] rxmat_M_real_2_address0;
reg    rxmat_M_real_2_ce0;
reg    rxmat_M_real_2_we0;
wire   [31:0] rxmat_M_real_2_q0;
reg    rxmat_M_real_2_ce1;
wire   [31:0] rxmat_M_real_2_q1;
reg   [11:0] rxmat_M_real_3_address0;
reg    rxmat_M_real_3_ce0;
reg    rxmat_M_real_3_we0;
wire   [31:0] rxmat_M_real_3_q0;
reg    rxmat_M_real_3_ce1;
wire   [31:0] rxmat_M_real_3_q1;
reg   [11:0] rxmat_M_imag_0_address0;
reg    rxmat_M_imag_0_ce0;
reg    rxmat_M_imag_0_we0;
wire   [31:0] rxmat_M_imag_0_q0;
reg    rxmat_M_imag_0_ce1;
wire   [31:0] rxmat_M_imag_0_q1;
reg   [11:0] rxmat_M_imag_1_address0;
reg    rxmat_M_imag_1_ce0;
reg    rxmat_M_imag_1_we0;
wire   [31:0] rxmat_M_imag_1_q0;
reg    rxmat_M_imag_1_ce1;
wire   [31:0] rxmat_M_imag_1_q1;
reg   [11:0] rxmat_M_imag_2_address0;
reg    rxmat_M_imag_2_ce0;
reg    rxmat_M_imag_2_we0;
wire   [31:0] rxmat_M_imag_2_q0;
reg    rxmat_M_imag_2_ce1;
wire   [31:0] rxmat_M_imag_2_q1;
reg   [11:0] rxmat_M_imag_3_address0;
reg    rxmat_M_imag_3_ce0;
reg    rxmat_M_imag_3_we0;
wire   [31:0] rxmat_M_imag_3_q0;
reg    rxmat_M_imag_3_ce1;
wire   [31:0] rxmat_M_imag_3_q1;
reg   [11:0] xmat_M_real_0_address0;
reg    xmat_M_real_0_ce0;
reg    xmat_M_real_0_we0;
wire   [31:0] xmat_M_real_0_q0;
reg    xmat_M_real_0_ce1;
wire   [31:0] xmat_M_real_0_q1;
reg   [11:0] xmat_M_real_1_address0;
reg    xmat_M_real_1_ce0;
reg    xmat_M_real_1_we0;
wire   [31:0] xmat_M_real_1_q0;
reg    xmat_M_real_1_ce1;
wire   [31:0] xmat_M_real_1_q1;
reg   [11:0] xmat_M_real_2_address0;
reg    xmat_M_real_2_ce0;
reg    xmat_M_real_2_we0;
wire   [31:0] xmat_M_real_2_q0;
reg    xmat_M_real_2_ce1;
wire   [31:0] xmat_M_real_2_q1;
reg   [11:0] xmat_M_real_3_address0;
reg    xmat_M_real_3_ce0;
reg    xmat_M_real_3_we0;
wire   [31:0] xmat_M_real_3_q0;
reg    xmat_M_real_3_ce1;
wire   [31:0] xmat_M_real_3_q1;
reg   [11:0] xmat_M_imag_0_address0;
reg    xmat_M_imag_0_ce0;
reg    xmat_M_imag_0_we0;
wire   [31:0] xmat_M_imag_0_q0;
reg    xmat_M_imag_0_ce1;
wire   [31:0] xmat_M_imag_0_q1;
reg   [11:0] xmat_M_imag_1_address0;
reg    xmat_M_imag_1_ce0;
reg    xmat_M_imag_1_we0;
wire   [31:0] xmat_M_imag_1_q0;
reg    xmat_M_imag_1_ce1;
wire   [31:0] xmat_M_imag_1_q1;
reg   [11:0] xmat_M_imag_2_address0;
reg    xmat_M_imag_2_ce0;
reg    xmat_M_imag_2_we0;
wire   [31:0] xmat_M_imag_2_q0;
reg    xmat_M_imag_2_ce1;
wire   [31:0] xmat_M_imag_2_q1;
reg   [11:0] xmat_M_imag_3_address0;
reg    xmat_M_imag_3_ce0;
reg    xmat_M_imag_3_we0;
wire   [31:0] xmat_M_imag_3_q0;
reg    xmat_M_imag_3_ce1;
wire   [31:0] xmat_M_imag_3_q1;
reg   [5:0] mulOut_M_real_0_address0;
reg    mulOut_M_real_0_ce0;
reg    mulOut_M_real_0_we0;
wire   [31:0] mulOut_M_real_0_q0;
reg   [5:0] mulOut_M_real_1_address0;
reg    mulOut_M_real_1_ce0;
reg    mulOut_M_real_1_we0;
wire   [31:0] mulOut_M_real_1_q0;
reg   [5:0] mulOut_M_real_2_address0;
reg    mulOut_M_real_2_ce0;
reg    mulOut_M_real_2_we0;
wire   [31:0] mulOut_M_real_2_q0;
reg   [5:0] mulOut_M_real_3_address0;
reg    mulOut_M_real_3_ce0;
reg    mulOut_M_real_3_we0;
wire   [31:0] mulOut_M_real_3_q0;
reg   [5:0] mulOut_M_imag_0_address0;
reg    mulOut_M_imag_0_ce0;
reg    mulOut_M_imag_0_we0;
wire   [31:0] mulOut_M_imag_0_q0;
reg   [5:0] mulOut_M_imag_1_address0;
reg    mulOut_M_imag_1_ce0;
reg    mulOut_M_imag_1_we0;
wire   [31:0] mulOut_M_imag_1_q0;
reg   [5:0] mulOut_M_imag_2_address0;
reg    mulOut_M_imag_2_ce0;
reg    mulOut_M_imag_2_we0;
wire   [31:0] mulOut_M_imag_2_q0;
reg   [5:0] mulOut_M_imag_3_address0;
reg    mulOut_M_imag_3_ce0;
reg    mulOut_M_imag_3_we0;
wire   [31:0] mulOut_M_imag_3_q0;
reg    in_stream_TDATA_blk_n;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln46_fu_679_p2;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln57_fu_783_p2;
reg    out_stream_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln71_reg_980;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] icmp_ln71_reg_980_pp0_iter1_reg;
reg   [8:0] i_2_reg_578;
wire   [7:0] add_ln36_fu_655_p2;
wire    ap_CS_fsm_state2;
wire   [8:0] i_fu_673_p2;
reg   [8:0] i_reg_939;
wire    ap_CS_fsm_state3;
wire   [6:0] j_fu_685_p2;
reg    ap_block_state4;
wire   [6:0] i_4_fu_751_p2;
reg   [6:0] i_4_reg_958;
wire    ap_CS_fsm_state5;
wire   [1:0] trunc_ln60_fu_757_p1;
reg   [1:0] trunc_ln60_reg_963;
wire   [0:0] icmp_ln56_fu_745_p2;
wire   [13:0] zext_ln57_fu_779_p1;
reg   [13:0] zext_ln57_reg_967;
wire   [8:0] j_2_fu_789_p2;
reg    ap_block_state6;
wire   [0:0] icmp_ln71_fu_836_p2;
wire    ap_block_state8_pp0_stage0_iter0;
wire    ap_block_state9_pp0_stage0_iter1;
reg    ap_block_state9_io;
wire    ap_block_state10_pp0_stage0_iter2;
reg    ap_block_state10_io;
reg    ap_block_pp0_stage0_11001;
wire   [8:0] i_3_fu_842_p2;
reg    ap_enable_reg_pp0_iter0;
reg   [2:0] lshr_ln1_reg_989;
wire   [0:0] valOut_last_V_fu_874_p2;
reg   [0:0] valOut_last_V_reg_1034;
wire    ap_CS_fsm_state7;
wire    grp_DiagMatMul_fu_589_ap_ready;
wire    grp_DiagMatMul_fu_589_ap_done;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state8;
wire    grp_DiagMatMul_fu_589_ap_start;
wire    grp_DiagMatMul_fu_589_ap_idle;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_real_address0;
wire    grp_DiagMatMul_fu_589_A_M_real_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_real_address1;
wire    grp_DiagMatMul_fu_589_A_M_real_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_real1_address0;
wire    grp_DiagMatMul_fu_589_A_M_real1_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_real1_address1;
wire    grp_DiagMatMul_fu_589_A_M_real1_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_real2_address0;
wire    grp_DiagMatMul_fu_589_A_M_real2_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_real2_address1;
wire    grp_DiagMatMul_fu_589_A_M_real2_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_real3_address0;
wire    grp_DiagMatMul_fu_589_A_M_real3_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_real3_address1;
wire    grp_DiagMatMul_fu_589_A_M_real3_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_imag_address0;
wire    grp_DiagMatMul_fu_589_A_M_imag_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_imag_address1;
wire    grp_DiagMatMul_fu_589_A_M_imag_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_imag4_address0;
wire    grp_DiagMatMul_fu_589_A_M_imag4_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_imag4_address1;
wire    grp_DiagMatMul_fu_589_A_M_imag4_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_imag5_address0;
wire    grp_DiagMatMul_fu_589_A_M_imag5_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_imag5_address1;
wire    grp_DiagMatMul_fu_589_A_M_imag5_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_imag6_address0;
wire    grp_DiagMatMul_fu_589_A_M_imag6_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_A_M_imag6_address1;
wire    grp_DiagMatMul_fu_589_A_M_imag6_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_real_0_address0;
wire    grp_DiagMatMul_fu_589_B_M_real_0_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_real_0_address1;
wire    grp_DiagMatMul_fu_589_B_M_real_0_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_real_1_address0;
wire    grp_DiagMatMul_fu_589_B_M_real_1_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_real_1_address1;
wire    grp_DiagMatMul_fu_589_B_M_real_1_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_real_2_address0;
wire    grp_DiagMatMul_fu_589_B_M_real_2_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_real_2_address1;
wire    grp_DiagMatMul_fu_589_B_M_real_2_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_real_3_address0;
wire    grp_DiagMatMul_fu_589_B_M_real_3_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_real_3_address1;
wire    grp_DiagMatMul_fu_589_B_M_real_3_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_imag_0_address0;
wire    grp_DiagMatMul_fu_589_B_M_imag_0_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_imag_0_address1;
wire    grp_DiagMatMul_fu_589_B_M_imag_0_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_imag_1_address0;
wire    grp_DiagMatMul_fu_589_B_M_imag_1_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_imag_1_address1;
wire    grp_DiagMatMul_fu_589_B_M_imag_1_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_imag_2_address0;
wire    grp_DiagMatMul_fu_589_B_M_imag_2_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_imag_2_address1;
wire    grp_DiagMatMul_fu_589_B_M_imag_2_ce1;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_imag_3_address0;
wire    grp_DiagMatMul_fu_589_B_M_imag_3_ce0;
wire   [11:0] grp_DiagMatMul_fu_589_B_M_imag_3_address1;
wire    grp_DiagMatMul_fu_589_B_M_imag_3_ce1;
wire   [5:0] grp_DiagMatMul_fu_589_C_M_real_0_address0;
wire    grp_DiagMatMul_fu_589_C_M_real_0_ce0;
wire    grp_DiagMatMul_fu_589_C_M_real_0_we0;
wire   [31:0] grp_DiagMatMul_fu_589_C_M_real_0_d0;
wire   [5:0] grp_DiagMatMul_fu_589_C_M_real_1_address0;
wire    grp_DiagMatMul_fu_589_C_M_real_1_ce0;
wire    grp_DiagMatMul_fu_589_C_M_real_1_we0;
wire   [31:0] grp_DiagMatMul_fu_589_C_M_real_1_d0;
wire   [5:0] grp_DiagMatMul_fu_589_C_M_real_2_address0;
wire    grp_DiagMatMul_fu_589_C_M_real_2_ce0;
wire    grp_DiagMatMul_fu_589_C_M_real_2_we0;
wire   [31:0] grp_DiagMatMul_fu_589_C_M_real_2_d0;
wire   [5:0] grp_DiagMatMul_fu_589_C_M_real_3_address0;
wire    grp_DiagMatMul_fu_589_C_M_real_3_ce0;
wire    grp_DiagMatMul_fu_589_C_M_real_3_we0;
wire   [31:0] grp_DiagMatMul_fu_589_C_M_real_3_d0;
wire   [5:0] grp_DiagMatMul_fu_589_C_M_imag_0_address0;
wire    grp_DiagMatMul_fu_589_C_M_imag_0_ce0;
wire    grp_DiagMatMul_fu_589_C_M_imag_0_we0;
wire   [31:0] grp_DiagMatMul_fu_589_C_M_imag_0_d0;
wire   [5:0] grp_DiagMatMul_fu_589_C_M_imag_1_address0;
wire    grp_DiagMatMul_fu_589_C_M_imag_1_ce0;
wire    grp_DiagMatMul_fu_589_C_M_imag_1_we0;
wire   [31:0] grp_DiagMatMul_fu_589_C_M_imag_1_d0;
wire   [5:0] grp_DiagMatMul_fu_589_C_M_imag_2_address0;
wire    grp_DiagMatMul_fu_589_C_M_imag_2_ce0;
wire    grp_DiagMatMul_fu_589_C_M_imag_2_we0;
wire   [31:0] grp_DiagMatMul_fu_589_C_M_imag_2_d0;
wire   [5:0] grp_DiagMatMul_fu_589_C_M_imag_3_address0;
wire    grp_DiagMatMul_fu_589_C_M_imag_3_ce0;
wire    grp_DiagMatMul_fu_589_C_M_imag_3_we0;
wire   [31:0] grp_DiagMatMul_fu_589_C_M_imag_3_d0;
reg   [7:0] phi_ln36_reg_522;
wire   [0:0] icmp_ln36_fu_661_p2;
reg   [8:0] i_0_reg_533;
reg   [6:0] j_0_reg_545;
wire   [0:0] icmp_ln45_fu_667_p2;
reg   [6:0] i_1_reg_556;
reg   [8:0] j_1_reg_567;
reg    grp_DiagMatMul_fu_589_ap_start_reg;
wire   [63:0] zext_ln49_fu_713_p1;
wire   [63:0] zext_ln60_1_fu_804_p1;
wire   [63:0] zext_ln1079_fu_862_p1;
wire    ap_block_pp0_stage0_01001;
wire   [2:0] trunc_ln49_1_fu_691_p4;
wire   [31:0] bitcast_ln49_fu_725_p1;
wire   [31:0] bitcast_ln52_fu_737_p1;
wire   [31:0] bitcast_ln60_fu_816_p1;
wire   [31:0] bitcast_ln63_fu_828_p1;
wire   [3:0] trunc_ln49_fu_701_p1;
wire   [12:0] tmp_7_fu_705_p3;
wire   [31:0] grp_fu_645_p4;
wire   [31:0] trunc_ln681_fu_733_p1;
wire   [4:0] lshr_ln_fu_761_p4;
wire   [12:0] tmp_6_fu_771_p3;
wire   [13:0] zext_ln60_fu_795_p1;
wire   [13:0] add_ln60_fu_799_p2;
wire   [31:0] trunc_ln681_1_fu_824_p1;
wire   [5:0] trunc_ln1079_fu_858_p1;
wire   [31:0] zext_ln1079_1_fu_880_p1;
wire   [31:0] tmp_3_fu_883_p6;
wire   [31:0] tmp_4_fu_901_p6;
wire   [31:0] bitcast_ln74_fu_897_p1;
wire   [31:0] bitcast_ln77_fu_915_p1;
wire    ap_CS_fsm_state11;
wire    regslice_both_out_stream_V_data_V_U_apdone_blk;
reg   [8:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    regslice_both_in_stream_V_data_V_U_apdone_blk;
wire   [63:0] in_stream_TDATA_int;
wire    in_stream_TVALID_int;
reg    in_stream_TREADY_int;
wire    regslice_both_in_stream_V_data_V_U_ack_in;
wire    regslice_both_in_stream_V_keep_V_U_apdone_blk;
wire   [7:0] in_stream_TKEEP_int;
wire    regslice_both_in_stream_V_keep_V_U_vld_out;
wire    regslice_both_in_stream_V_keep_V_U_ack_in;
wire    regslice_both_in_stream_V_strb_V_U_apdone_blk;
wire   [7:0] in_stream_TSTRB_int;
wire    regslice_both_in_stream_V_strb_V_U_vld_out;
wire    regslice_both_in_stream_V_strb_V_U_ack_in;
wire    regslice_both_in_stream_V_last_V_U_apdone_blk;
wire   [0:0] in_stream_TLAST_int;
wire    regslice_both_in_stream_V_last_V_U_vld_out;
wire    regslice_both_in_stream_V_last_V_U_ack_in;
wire   [63:0] out_stream_TDATA_int;
reg    out_stream_TVALID_int;
wire    out_stream_TREADY_int;
wire    regslice_both_out_stream_V_data_V_U_vld_out;
wire    regslice_both_out_stream_V_keep_V_U_apdone_blk;
wire    regslice_both_out_stream_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_keep_V_U_vld_out;
wire    regslice_both_out_stream_V_strb_V_U_apdone_blk;
wire    regslice_both_out_stream_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_strb_V_U_vld_out;
wire    regslice_both_out_stream_V_last_V_U_apdone_blk;
wire    regslice_both_out_stream_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_stream_V_last_V_U_vld_out;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 grp_DiagMatMul_fu_589_ap_start_reg = 1'b0;
end

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
rxmat_M_real_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rxmat_M_real_0_address0),
    .ce0(rxmat_M_real_0_ce0),
    .we0(rxmat_M_real_0_we0),
    .d0(bitcast_ln52_fu_737_p1),
    .q0(rxmat_M_real_0_q0),
    .address1(grp_DiagMatMul_fu_589_A_M_real_address1),
    .ce1(rxmat_M_real_0_ce1),
    .q1(rxmat_M_real_0_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
rxmat_M_real_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rxmat_M_real_1_address0),
    .ce0(rxmat_M_real_1_ce0),
    .we0(rxmat_M_real_1_we0),
    .d0(bitcast_ln52_fu_737_p1),
    .q0(rxmat_M_real_1_q0),
    .address1(grp_DiagMatMul_fu_589_A_M_real1_address1),
    .ce1(rxmat_M_real_1_ce1),
    .q1(rxmat_M_real_1_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
rxmat_M_real_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rxmat_M_real_2_address0),
    .ce0(rxmat_M_real_2_ce0),
    .we0(rxmat_M_real_2_we0),
    .d0(bitcast_ln52_fu_737_p1),
    .q0(rxmat_M_real_2_q0),
    .address1(grp_DiagMatMul_fu_589_A_M_real2_address1),
    .ce1(rxmat_M_real_2_ce1),
    .q1(rxmat_M_real_2_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
rxmat_M_real_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rxmat_M_real_3_address0),
    .ce0(rxmat_M_real_3_ce0),
    .we0(rxmat_M_real_3_we0),
    .d0(bitcast_ln52_fu_737_p1),
    .q0(rxmat_M_real_3_q0),
    .address1(grp_DiagMatMul_fu_589_A_M_real3_address1),
    .ce1(rxmat_M_real_3_ce1),
    .q1(rxmat_M_real_3_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
rxmat_M_imag_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rxmat_M_imag_0_address0),
    .ce0(rxmat_M_imag_0_ce0),
    .we0(rxmat_M_imag_0_we0),
    .d0(bitcast_ln49_fu_725_p1),
    .q0(rxmat_M_imag_0_q0),
    .address1(grp_DiagMatMul_fu_589_A_M_imag_address1),
    .ce1(rxmat_M_imag_0_ce1),
    .q1(rxmat_M_imag_0_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
rxmat_M_imag_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rxmat_M_imag_1_address0),
    .ce0(rxmat_M_imag_1_ce0),
    .we0(rxmat_M_imag_1_we0),
    .d0(bitcast_ln49_fu_725_p1),
    .q0(rxmat_M_imag_1_q0),
    .address1(grp_DiagMatMul_fu_589_A_M_imag4_address1),
    .ce1(rxmat_M_imag_1_ce1),
    .q1(rxmat_M_imag_1_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
rxmat_M_imag_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rxmat_M_imag_2_address0),
    .ce0(rxmat_M_imag_2_ce0),
    .we0(rxmat_M_imag_2_we0),
    .d0(bitcast_ln49_fu_725_p1),
    .q0(rxmat_M_imag_2_q0),
    .address1(grp_DiagMatMul_fu_589_A_M_imag5_address1),
    .ce1(rxmat_M_imag_2_ce1),
    .q1(rxmat_M_imag_2_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
rxmat_M_imag_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rxmat_M_imag_3_address0),
    .ce0(rxmat_M_imag_3_ce0),
    .we0(rxmat_M_imag_3_we0),
    .d0(bitcast_ln49_fu_725_p1),
    .q0(rxmat_M_imag_3_q0),
    .address1(grp_DiagMatMul_fu_589_A_M_imag6_address1),
    .ce1(rxmat_M_imag_3_ce1),
    .q1(rxmat_M_imag_3_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
xmat_M_real_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xmat_M_real_0_address0),
    .ce0(xmat_M_real_0_ce0),
    .we0(xmat_M_real_0_we0),
    .d0(bitcast_ln63_fu_828_p1),
    .q0(xmat_M_real_0_q0),
    .address1(grp_DiagMatMul_fu_589_B_M_real_0_address1),
    .ce1(xmat_M_real_0_ce1),
    .q1(xmat_M_real_0_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
xmat_M_real_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xmat_M_real_1_address0),
    .ce0(xmat_M_real_1_ce0),
    .we0(xmat_M_real_1_we0),
    .d0(bitcast_ln63_fu_828_p1),
    .q0(xmat_M_real_1_q0),
    .address1(grp_DiagMatMul_fu_589_B_M_real_1_address1),
    .ce1(xmat_M_real_1_ce1),
    .q1(xmat_M_real_1_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
xmat_M_real_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xmat_M_real_2_address0),
    .ce0(xmat_M_real_2_ce0),
    .we0(xmat_M_real_2_we0),
    .d0(bitcast_ln63_fu_828_p1),
    .q0(xmat_M_real_2_q0),
    .address1(grp_DiagMatMul_fu_589_B_M_real_2_address1),
    .ce1(xmat_M_real_2_ce1),
    .q1(xmat_M_real_2_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
xmat_M_real_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xmat_M_real_3_address0),
    .ce0(xmat_M_real_3_ce0),
    .we0(xmat_M_real_3_we0),
    .d0(bitcast_ln63_fu_828_p1),
    .q0(xmat_M_real_3_q0),
    .address1(grp_DiagMatMul_fu_589_B_M_real_3_address1),
    .ce1(xmat_M_real_3_ce1),
    .q1(xmat_M_real_3_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
xmat_M_imag_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xmat_M_imag_0_address0),
    .ce0(xmat_M_imag_0_ce0),
    .we0(xmat_M_imag_0_we0),
    .d0(bitcast_ln60_fu_816_p1),
    .q0(xmat_M_imag_0_q0),
    .address1(grp_DiagMatMul_fu_589_B_M_imag_0_address1),
    .ce1(xmat_M_imag_0_ce1),
    .q1(xmat_M_imag_0_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
xmat_M_imag_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xmat_M_imag_1_address0),
    .ce0(xmat_M_imag_1_ce0),
    .we0(xmat_M_imag_1_we0),
    .d0(bitcast_ln60_fu_816_p1),
    .q0(xmat_M_imag_1_q0),
    .address1(grp_DiagMatMul_fu_589_B_M_imag_1_address1),
    .ce1(xmat_M_imag_1_ce1),
    .q1(xmat_M_imag_1_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
xmat_M_imag_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xmat_M_imag_2_address0),
    .ce0(xmat_M_imag_2_ce0),
    .we0(xmat_M_imag_2_we0),
    .d0(bitcast_ln60_fu_816_p1),
    .q0(xmat_M_imag_2_q0),
    .address1(grp_DiagMatMul_fu_589_B_M_imag_2_address1),
    .ce1(xmat_M_imag_2_ce1),
    .q1(xmat_M_imag_2_q1)
);

matmul_rxmat_M_reeOg #(
    .DataWidth( 32 ),
    .AddressRange( 4096 ),
    .AddressWidth( 12 ))
xmat_M_imag_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(xmat_M_imag_3_address0),
    .ce0(xmat_M_imag_3_ce0),
    .we0(xmat_M_imag_3_we0),
    .d0(bitcast_ln60_fu_816_p1),
    .q0(xmat_M_imag_3_q0),
    .address1(grp_DiagMatMul_fu_589_B_M_imag_3_address1),
    .ce1(xmat_M_imag_3_ce1),
    .q1(xmat_M_imag_3_q1)
);

matmul_mulOut_M_rudo #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mulOut_M_real_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mulOut_M_real_0_address0),
    .ce0(mulOut_M_real_0_ce0),
    .we0(mulOut_M_real_0_we0),
    .d0(grp_DiagMatMul_fu_589_C_M_real_0_d0),
    .q0(mulOut_M_real_0_q0)
);

matmul_mulOut_M_rudo #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mulOut_M_real_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mulOut_M_real_1_address0),
    .ce0(mulOut_M_real_1_ce0),
    .we0(mulOut_M_real_1_we0),
    .d0(grp_DiagMatMul_fu_589_C_M_real_1_d0),
    .q0(mulOut_M_real_1_q0)
);

matmul_mulOut_M_rudo #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mulOut_M_real_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mulOut_M_real_2_address0),
    .ce0(mulOut_M_real_2_ce0),
    .we0(mulOut_M_real_2_we0),
    .d0(grp_DiagMatMul_fu_589_C_M_real_2_d0),
    .q0(mulOut_M_real_2_q0)
);

matmul_mulOut_M_rudo #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mulOut_M_real_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mulOut_M_real_3_address0),
    .ce0(mulOut_M_real_3_ce0),
    .we0(mulOut_M_real_3_we0),
    .d0(grp_DiagMatMul_fu_589_C_M_real_3_d0),
    .q0(mulOut_M_real_3_q0)
);

matmul_mulOut_M_rudo #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mulOut_M_imag_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mulOut_M_imag_0_address0),
    .ce0(mulOut_M_imag_0_ce0),
    .we0(mulOut_M_imag_0_we0),
    .d0(grp_DiagMatMul_fu_589_C_M_imag_0_d0),
    .q0(mulOut_M_imag_0_q0)
);

matmul_mulOut_M_rudo #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mulOut_M_imag_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mulOut_M_imag_1_address0),
    .ce0(mulOut_M_imag_1_ce0),
    .we0(mulOut_M_imag_1_we0),
    .d0(grp_DiagMatMul_fu_589_C_M_imag_1_d0),
    .q0(mulOut_M_imag_1_q0)
);

matmul_mulOut_M_rudo #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mulOut_M_imag_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mulOut_M_imag_2_address0),
    .ce0(mulOut_M_imag_2_ce0),
    .we0(mulOut_M_imag_2_we0),
    .d0(grp_DiagMatMul_fu_589_C_M_imag_2_d0),
    .q0(mulOut_M_imag_2_q0)
);

matmul_mulOut_M_rudo #(
    .DataWidth( 32 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
mulOut_M_imag_3_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(mulOut_M_imag_3_address0),
    .ce0(mulOut_M_imag_3_ce0),
    .we0(mulOut_M_imag_3_we0),
    .d0(grp_DiagMatMul_fu_589_C_M_imag_3_d0),
    .q0(mulOut_M_imag_3_q0)
);

matmul_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
matmul_control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

DiagMatMul grp_DiagMatMul_fu_589(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_DiagMatMul_fu_589_ap_start),
    .ap_done(grp_DiagMatMul_fu_589_ap_done),
    .ap_idle(grp_DiagMatMul_fu_589_ap_idle),
    .ap_ready(grp_DiagMatMul_fu_589_ap_ready),
    .A_M_real_address0(grp_DiagMatMul_fu_589_A_M_real_address0),
    .A_M_real_ce0(grp_DiagMatMul_fu_589_A_M_real_ce0),
    .A_M_real_q0(rxmat_M_real_0_q0),
    .A_M_real_address1(grp_DiagMatMul_fu_589_A_M_real_address1),
    .A_M_real_ce1(grp_DiagMatMul_fu_589_A_M_real_ce1),
    .A_M_real_q1(rxmat_M_real_0_q1),
    .A_M_real1_address0(grp_DiagMatMul_fu_589_A_M_real1_address0),
    .A_M_real1_ce0(grp_DiagMatMul_fu_589_A_M_real1_ce0),
    .A_M_real1_q0(rxmat_M_real_1_q0),
    .A_M_real1_address1(grp_DiagMatMul_fu_589_A_M_real1_address1),
    .A_M_real1_ce1(grp_DiagMatMul_fu_589_A_M_real1_ce1),
    .A_M_real1_q1(rxmat_M_real_1_q1),
    .A_M_real2_address0(grp_DiagMatMul_fu_589_A_M_real2_address0),
    .A_M_real2_ce0(grp_DiagMatMul_fu_589_A_M_real2_ce0),
    .A_M_real2_q0(rxmat_M_real_2_q0),
    .A_M_real2_address1(grp_DiagMatMul_fu_589_A_M_real2_address1),
    .A_M_real2_ce1(grp_DiagMatMul_fu_589_A_M_real2_ce1),
    .A_M_real2_q1(rxmat_M_real_2_q1),
    .A_M_real3_address0(grp_DiagMatMul_fu_589_A_M_real3_address0),
    .A_M_real3_ce0(grp_DiagMatMul_fu_589_A_M_real3_ce0),
    .A_M_real3_q0(rxmat_M_real_3_q0),
    .A_M_real3_address1(grp_DiagMatMul_fu_589_A_M_real3_address1),
    .A_M_real3_ce1(grp_DiagMatMul_fu_589_A_M_real3_ce1),
    .A_M_real3_q1(rxmat_M_real_3_q1),
    .A_M_imag_address0(grp_DiagMatMul_fu_589_A_M_imag_address0),
    .A_M_imag_ce0(grp_DiagMatMul_fu_589_A_M_imag_ce0),
    .A_M_imag_q0(rxmat_M_imag_0_q0),
    .A_M_imag_address1(grp_DiagMatMul_fu_589_A_M_imag_address1),
    .A_M_imag_ce1(grp_DiagMatMul_fu_589_A_M_imag_ce1),
    .A_M_imag_q1(rxmat_M_imag_0_q1),
    .A_M_imag4_address0(grp_DiagMatMul_fu_589_A_M_imag4_address0),
    .A_M_imag4_ce0(grp_DiagMatMul_fu_589_A_M_imag4_ce0),
    .A_M_imag4_q0(rxmat_M_imag_1_q0),
    .A_M_imag4_address1(grp_DiagMatMul_fu_589_A_M_imag4_address1),
    .A_M_imag4_ce1(grp_DiagMatMul_fu_589_A_M_imag4_ce1),
    .A_M_imag4_q1(rxmat_M_imag_1_q1),
    .A_M_imag5_address0(grp_DiagMatMul_fu_589_A_M_imag5_address0),
    .A_M_imag5_ce0(grp_DiagMatMul_fu_589_A_M_imag5_ce0),
    .A_M_imag5_q0(rxmat_M_imag_2_q0),
    .A_M_imag5_address1(grp_DiagMatMul_fu_589_A_M_imag5_address1),
    .A_M_imag5_ce1(grp_DiagMatMul_fu_589_A_M_imag5_ce1),
    .A_M_imag5_q1(rxmat_M_imag_2_q1),
    .A_M_imag6_address0(grp_DiagMatMul_fu_589_A_M_imag6_address0),
    .A_M_imag6_ce0(grp_DiagMatMul_fu_589_A_M_imag6_ce0),
    .A_M_imag6_q0(rxmat_M_imag_3_q0),
    .A_M_imag6_address1(grp_DiagMatMul_fu_589_A_M_imag6_address1),
    .A_M_imag6_ce1(grp_DiagMatMul_fu_589_A_M_imag6_ce1),
    .A_M_imag6_q1(rxmat_M_imag_3_q1),
    .B_M_real_0_address0(grp_DiagMatMul_fu_589_B_M_real_0_address0),
    .B_M_real_0_ce0(grp_DiagMatMul_fu_589_B_M_real_0_ce0),
    .B_M_real_0_q0(xmat_M_real_0_q0),
    .B_M_real_0_address1(grp_DiagMatMul_fu_589_B_M_real_0_address1),
    .B_M_real_0_ce1(grp_DiagMatMul_fu_589_B_M_real_0_ce1),
    .B_M_real_0_q1(xmat_M_real_0_q1),
    .B_M_real_1_address0(grp_DiagMatMul_fu_589_B_M_real_1_address0),
    .B_M_real_1_ce0(grp_DiagMatMul_fu_589_B_M_real_1_ce0),
    .B_M_real_1_q0(xmat_M_real_1_q0),
    .B_M_real_1_address1(grp_DiagMatMul_fu_589_B_M_real_1_address1),
    .B_M_real_1_ce1(grp_DiagMatMul_fu_589_B_M_real_1_ce1),
    .B_M_real_1_q1(xmat_M_real_1_q1),
    .B_M_real_2_address0(grp_DiagMatMul_fu_589_B_M_real_2_address0),
    .B_M_real_2_ce0(grp_DiagMatMul_fu_589_B_M_real_2_ce0),
    .B_M_real_2_q0(xmat_M_real_2_q0),
    .B_M_real_2_address1(grp_DiagMatMul_fu_589_B_M_real_2_address1),
    .B_M_real_2_ce1(grp_DiagMatMul_fu_589_B_M_real_2_ce1),
    .B_M_real_2_q1(xmat_M_real_2_q1),
    .B_M_real_3_address0(grp_DiagMatMul_fu_589_B_M_real_3_address0),
    .B_M_real_3_ce0(grp_DiagMatMul_fu_589_B_M_real_3_ce0),
    .B_M_real_3_q0(xmat_M_real_3_q0),
    .B_M_real_3_address1(grp_DiagMatMul_fu_589_B_M_real_3_address1),
    .B_M_real_3_ce1(grp_DiagMatMul_fu_589_B_M_real_3_ce1),
    .B_M_real_3_q1(xmat_M_real_3_q1),
    .B_M_imag_0_address0(grp_DiagMatMul_fu_589_B_M_imag_0_address0),
    .B_M_imag_0_ce0(grp_DiagMatMul_fu_589_B_M_imag_0_ce0),
    .B_M_imag_0_q0(xmat_M_imag_0_q0),
    .B_M_imag_0_address1(grp_DiagMatMul_fu_589_B_M_imag_0_address1),
    .B_M_imag_0_ce1(grp_DiagMatMul_fu_589_B_M_imag_0_ce1),
    .B_M_imag_0_q1(xmat_M_imag_0_q1),
    .B_M_imag_1_address0(grp_DiagMatMul_fu_589_B_M_imag_1_address0),
    .B_M_imag_1_ce0(grp_DiagMatMul_fu_589_B_M_imag_1_ce0),
    .B_M_imag_1_q0(xmat_M_imag_1_q0),
    .B_M_imag_1_address1(grp_DiagMatMul_fu_589_B_M_imag_1_address1),
    .B_M_imag_1_ce1(grp_DiagMatMul_fu_589_B_M_imag_1_ce1),
    .B_M_imag_1_q1(xmat_M_imag_1_q1),
    .B_M_imag_2_address0(grp_DiagMatMul_fu_589_B_M_imag_2_address0),
    .B_M_imag_2_ce0(grp_DiagMatMul_fu_589_B_M_imag_2_ce0),
    .B_M_imag_2_q0(xmat_M_imag_2_q0),
    .B_M_imag_2_address1(grp_DiagMatMul_fu_589_B_M_imag_2_address1),
    .B_M_imag_2_ce1(grp_DiagMatMul_fu_589_B_M_imag_2_ce1),
    .B_M_imag_2_q1(xmat_M_imag_2_q1),
    .B_M_imag_3_address0(grp_DiagMatMul_fu_589_B_M_imag_3_address0),
    .B_M_imag_3_ce0(grp_DiagMatMul_fu_589_B_M_imag_3_ce0),
    .B_M_imag_3_q0(xmat_M_imag_3_q0),
    .B_M_imag_3_address1(grp_DiagMatMul_fu_589_B_M_imag_3_address1),
    .B_M_imag_3_ce1(grp_DiagMatMul_fu_589_B_M_imag_3_ce1),
    .B_M_imag_3_q1(xmat_M_imag_3_q1),
    .C_M_real_0_address0(grp_DiagMatMul_fu_589_C_M_real_0_address0),
    .C_M_real_0_ce0(grp_DiagMatMul_fu_589_C_M_real_0_ce0),
    .C_M_real_0_we0(grp_DiagMatMul_fu_589_C_M_real_0_we0),
    .C_M_real_0_d0(grp_DiagMatMul_fu_589_C_M_real_0_d0),
    .C_M_real_1_address0(grp_DiagMatMul_fu_589_C_M_real_1_address0),
    .C_M_real_1_ce0(grp_DiagMatMul_fu_589_C_M_real_1_ce0),
    .C_M_real_1_we0(grp_DiagMatMul_fu_589_C_M_real_1_we0),
    .C_M_real_1_d0(grp_DiagMatMul_fu_589_C_M_real_1_d0),
    .C_M_real_2_address0(grp_DiagMatMul_fu_589_C_M_real_2_address0),
    .C_M_real_2_ce0(grp_DiagMatMul_fu_589_C_M_real_2_ce0),
    .C_M_real_2_we0(grp_DiagMatMul_fu_589_C_M_real_2_we0),
    .C_M_real_2_d0(grp_DiagMatMul_fu_589_C_M_real_2_d0),
    .C_M_real_3_address0(grp_DiagMatMul_fu_589_C_M_real_3_address0),
    .C_M_real_3_ce0(grp_DiagMatMul_fu_589_C_M_real_3_ce0),
    .C_M_real_3_we0(grp_DiagMatMul_fu_589_C_M_real_3_we0),
    .C_M_real_3_d0(grp_DiagMatMul_fu_589_C_M_real_3_d0),
    .C_M_imag_0_address0(grp_DiagMatMul_fu_589_C_M_imag_0_address0),
    .C_M_imag_0_ce0(grp_DiagMatMul_fu_589_C_M_imag_0_ce0),
    .C_M_imag_0_we0(grp_DiagMatMul_fu_589_C_M_imag_0_we0),
    .C_M_imag_0_d0(grp_DiagMatMul_fu_589_C_M_imag_0_d0),
    .C_M_imag_1_address0(grp_DiagMatMul_fu_589_C_M_imag_1_address0),
    .C_M_imag_1_ce0(grp_DiagMatMul_fu_589_C_M_imag_1_ce0),
    .C_M_imag_1_we0(grp_DiagMatMul_fu_589_C_M_imag_1_we0),
    .C_M_imag_1_d0(grp_DiagMatMul_fu_589_C_M_imag_1_d0),
    .C_M_imag_2_address0(grp_DiagMatMul_fu_589_C_M_imag_2_address0),
    .C_M_imag_2_ce0(grp_DiagMatMul_fu_589_C_M_imag_2_ce0),
    .C_M_imag_2_we0(grp_DiagMatMul_fu_589_C_M_imag_2_we0),
    .C_M_imag_2_d0(grp_DiagMatMul_fu_589_C_M_imag_2_d0),
    .C_M_imag_3_address0(grp_DiagMatMul_fu_589_C_M_imag_3_address0),
    .C_M_imag_3_ce0(grp_DiagMatMul_fu_589_C_M_imag_3_ce0),
    .C_M_imag_3_we0(grp_DiagMatMul_fu_589_C_M_imag_3_we0),
    .C_M_imag_3_d0(grp_DiagMatMul_fu_589_C_M_imag_3_d0)
);

matmul_mux_432_32CeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matmul_mux_432_32CeG_U44(
    .din0(mulOut_M_imag_0_q0),
    .din1(mulOut_M_imag_1_q0),
    .din2(mulOut_M_imag_2_q0),
    .din3(mulOut_M_imag_3_q0),
    .din4(zext_ln1079_1_fu_880_p1),
    .dout(tmp_3_fu_883_p6)
);

matmul_mux_432_32CeG #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
matmul_mux_432_32CeG_U45(
    .din0(mulOut_M_real_0_q0),
    .din1(mulOut_M_real_1_q0),
    .din2(mulOut_M_real_2_q0),
    .din3(mulOut_M_real_3_q0),
    .din4(zext_ln1079_1_fu_880_p1),
    .dout(tmp_4_fu_901_p6)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_in_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TDATA),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_data_V_U_ack_in),
    .data_out(in_stream_TDATA_int),
    .vld_out(in_stream_TVALID_int),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TKEEP),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_keep_V_U_ack_in),
    .data_out(in_stream_TKEEP_int),
    .vld_out(regslice_both_in_stream_V_keep_V_U_vld_out),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_in_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TSTRB),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_strb_V_U_ack_in),
    .data_out(in_stream_TSTRB_int),
    .vld_out(regslice_both_in_stream_V_strb_V_U_vld_out),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_stream_TLAST),
    .vld_in(in_stream_TVALID),
    .ack_in(regslice_both_in_stream_V_last_V_U_ack_in),
    .data_out(in_stream_TLAST_int),
    .vld_out(regslice_both_in_stream_V_last_V_U_vld_out),
    .ack_out(in_stream_TREADY_int),
    .apdone_blk(regslice_both_in_stream_V_last_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 64 ))
regslice_both_out_stream_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_TDATA_int),
    .vld_in(out_stream_TVALID_int),
    .ack_in(out_stream_TREADY_int),
    .data_out(out_stream_TDATA),
    .vld_out(regslice_both_out_stream_V_data_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_data_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_stream_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd255),
    .vld_in(out_stream_TVALID_int),
    .ack_in(regslice_both_out_stream_V_keep_V_U_ack_in_dummy),
    .data_out(out_stream_TKEEP),
    .vld_out(regslice_both_out_stream_V_keep_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_keep_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_stream_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(8'd255),
    .vld_in(out_stream_TVALID_int),
    .ack_in(regslice_both_out_stream_V_strb_V_U_ack_in_dummy),
    .data_out(out_stream_TSTRB),
    .vld_out(regslice_both_out_stream_V_strb_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_strb_V_U_apdone_blk)
);

regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_stream_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(valOut_last_V_reg_1034),
    .vld_in(out_stream_TVALID_int),
    .ack_in(regslice_both_out_stream_V_last_V_U_ack_in_dummy),
    .data_out(out_stream_TLAST),
    .vld_out(regslice_both_out_stream_V_last_V_U_vld_out),
    .ack_out(out_stream_TREADY),
    .apdone_blk(regslice_both_out_stream_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state8) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((grp_DiagMatMul_fu_589_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state8)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state8);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((grp_DiagMatMul_fu_589_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_DiagMatMul_fu_589_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln56_fu_745_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_DiagMatMul_fu_589_ap_start_reg <= 1'b1;
        end else if ((grp_DiagMatMul_fu_589_ap_ready == 1'b1)) begin
            grp_DiagMatMul_fu_589_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_0_reg_533 <= 9'd0;
    end else if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln46_fu_679_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        i_0_reg_533 <= i_reg_939;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln45_fu_667_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_1_reg_556 <= 7'd0;
    end else if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln57_fu_783_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
        i_1_reg_556 <= i_4_reg_958;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln71_fu_836_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_2_reg_578 <= i_3_fu_842_p2;
    end else if (((grp_DiagMatMul_fu_589_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        i_2_reg_578 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        j_0_reg_545 <= j_fu_685_p2;
    end else if (((icmp_ln45_fu_667_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        j_0_reg_545 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        j_1_reg_567 <= j_2_fu_789_p2;
    end else if (((icmp_ln56_fu_745_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        j_1_reg_567 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln36_fu_661_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        phi_ln36_reg_522 <= add_ln36_fu_655_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        phi_ln36_reg_522 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        i_4_reg_958 <= i_4_fu_751_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_reg_939 <= i_fu_673_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln71_reg_980 <= icmp_ln71_fu_836_p2;
        icmp_ln71_reg_980_pp0_iter1_reg <= icmp_ln71_reg_980;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln71_fu_836_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln1_reg_989 <= {{i_2_reg_578[8:6]}};
        valOut_last_V_reg_1034 <= valOut_last_V_fu_874_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln56_fu_745_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        trunc_ln60_reg_963 <= trunc_ln60_fu_757_p1;
        zext_ln57_reg_967[12 : 8] <= zext_ln57_fu_779_p1[12 : 8];
    end
end

always @ (*) begin
    if ((icmp_ln71_fu_836_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state8 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state8 = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | ((icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        in_stream_TDATA_blk_n = in_stream_TVALID_int;
    end else begin
        in_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((regslice_both_in_stream_V_data_V_U_ack_in == 1'b1) & (in_stream_TVALID == 1'b1))) begin
        in_stream_TREADY = 1'b1;
    end else begin
        in_stream_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6)) | (~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4)))) begin
        in_stream_TREADY_int = 1'b1;
    end else begin
        in_stream_TREADY_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_imag_0_address0 = zext_ln1079_fu_862_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_0_address0 = grp_DiagMatMul_fu_589_C_M_imag_0_address0;
    end else begin
        mulOut_M_imag_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_imag_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_0_ce0 = grp_DiagMatMul_fu_589_C_M_imag_0_ce0;
    end else begin
        mulOut_M_imag_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_0_we0 = grp_DiagMatMul_fu_589_C_M_imag_0_we0;
    end else begin
        mulOut_M_imag_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_imag_1_address0 = zext_ln1079_fu_862_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_1_address0 = grp_DiagMatMul_fu_589_C_M_imag_1_address0;
    end else begin
        mulOut_M_imag_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_imag_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_1_ce0 = grp_DiagMatMul_fu_589_C_M_imag_1_ce0;
    end else begin
        mulOut_M_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_1_we0 = grp_DiagMatMul_fu_589_C_M_imag_1_we0;
    end else begin
        mulOut_M_imag_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_imag_2_address0 = zext_ln1079_fu_862_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_2_address0 = grp_DiagMatMul_fu_589_C_M_imag_2_address0;
    end else begin
        mulOut_M_imag_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_imag_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_2_ce0 = grp_DiagMatMul_fu_589_C_M_imag_2_ce0;
    end else begin
        mulOut_M_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_2_we0 = grp_DiagMatMul_fu_589_C_M_imag_2_we0;
    end else begin
        mulOut_M_imag_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_imag_3_address0 = zext_ln1079_fu_862_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_3_address0 = grp_DiagMatMul_fu_589_C_M_imag_3_address0;
    end else begin
        mulOut_M_imag_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_imag_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_3_ce0 = grp_DiagMatMul_fu_589_C_M_imag_3_ce0;
    end else begin
        mulOut_M_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_imag_3_we0 = grp_DiagMatMul_fu_589_C_M_imag_3_we0;
    end else begin
        mulOut_M_imag_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_real_0_address0 = zext_ln1079_fu_862_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_0_address0 = grp_DiagMatMul_fu_589_C_M_real_0_address0;
    end else begin
        mulOut_M_real_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_real_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_0_ce0 = grp_DiagMatMul_fu_589_C_M_real_0_ce0;
    end else begin
        mulOut_M_real_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_0_we0 = grp_DiagMatMul_fu_589_C_M_real_0_we0;
    end else begin
        mulOut_M_real_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_real_1_address0 = zext_ln1079_fu_862_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_1_address0 = grp_DiagMatMul_fu_589_C_M_real_1_address0;
    end else begin
        mulOut_M_real_1_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_real_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_1_ce0 = grp_DiagMatMul_fu_589_C_M_real_1_ce0;
    end else begin
        mulOut_M_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_1_we0 = grp_DiagMatMul_fu_589_C_M_real_1_we0;
    end else begin
        mulOut_M_real_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_real_2_address0 = zext_ln1079_fu_862_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_2_address0 = grp_DiagMatMul_fu_589_C_M_real_2_address0;
    end else begin
        mulOut_M_real_2_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_real_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_2_ce0 = grp_DiagMatMul_fu_589_C_M_real_2_ce0;
    end else begin
        mulOut_M_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_2_we0 = grp_DiagMatMul_fu_589_C_M_real_2_we0;
    end else begin
        mulOut_M_real_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_real_3_address0 = zext_ln1079_fu_862_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_3_address0 = grp_DiagMatMul_fu_589_C_M_real_3_address0;
    end else begin
        mulOut_M_real_3_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mulOut_M_real_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_3_ce0 = grp_DiagMatMul_fu_589_C_M_real_3_ce0;
    end else begin
        mulOut_M_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        mulOut_M_real_3_we0 = grp_DiagMatMul_fu_589_C_M_real_3_we0;
    end else begin
        mulOut_M_real_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (icmp_ln71_reg_980_pp0_iter1_reg == 1'd0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (icmp_ln71_reg_980 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_stream_TDATA_blk_n = out_stream_TREADY_int;
    end else begin
        out_stream_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln71_reg_980 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_TVALID_int = 1'b1;
    end else begin
        out_stream_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rxmat_M_imag_0_address0 = zext_ln49_fu_713_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_0_address0 = grp_DiagMatMul_fu_589_A_M_imag_address0;
    end else begin
        rxmat_M_imag_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_imag_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_0_ce0 = grp_DiagMatMul_fu_589_A_M_imag_ce0;
    end else begin
        rxmat_M_imag_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_0_ce1 = grp_DiagMatMul_fu_589_A_M_imag_ce1;
    end else begin
        rxmat_M_imag_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln49_1_fu_691_p4 == 3'd0) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_imag_0_we0 = 1'b1;
    end else begin
        rxmat_M_imag_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rxmat_M_imag_1_address0 = zext_ln49_fu_713_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_1_address0 = grp_DiagMatMul_fu_589_A_M_imag4_address0;
    end else begin
        rxmat_M_imag_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_imag_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_1_ce0 = grp_DiagMatMul_fu_589_A_M_imag4_ce0;
    end else begin
        rxmat_M_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_1_ce1 = grp_DiagMatMul_fu_589_A_M_imag4_ce1;
    end else begin
        rxmat_M_imag_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln49_1_fu_691_p4 == 3'd1) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_imag_1_we0 = 1'b1;
    end else begin
        rxmat_M_imag_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rxmat_M_imag_2_address0 = zext_ln49_fu_713_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_2_address0 = grp_DiagMatMul_fu_589_A_M_imag5_address0;
    end else begin
        rxmat_M_imag_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_imag_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_2_ce0 = grp_DiagMatMul_fu_589_A_M_imag5_ce0;
    end else begin
        rxmat_M_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_2_ce1 = grp_DiagMatMul_fu_589_A_M_imag5_ce1;
    end else begin
        rxmat_M_imag_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln49_1_fu_691_p4 == 3'd2) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_imag_2_we0 = 1'b1;
    end else begin
        rxmat_M_imag_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rxmat_M_imag_3_address0 = zext_ln49_fu_713_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_3_address0 = grp_DiagMatMul_fu_589_A_M_imag6_address0;
    end else begin
        rxmat_M_imag_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_imag_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_3_ce0 = grp_DiagMatMul_fu_589_A_M_imag6_ce0;
    end else begin
        rxmat_M_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_imag_3_ce1 = grp_DiagMatMul_fu_589_A_M_imag6_ce1;
    end else begin
        rxmat_M_imag_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & ~(trunc_ln49_1_fu_691_p4 == 3'd0) & ~(trunc_ln49_1_fu_691_p4 == 3'd1) & ~(trunc_ln49_1_fu_691_p4 == 3'd2) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_imag_3_we0 = 1'b1;
    end else begin
        rxmat_M_imag_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rxmat_M_real_0_address0 = zext_ln49_fu_713_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_0_address0 = grp_DiagMatMul_fu_589_A_M_real_address0;
    end else begin
        rxmat_M_real_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_real_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_0_ce0 = grp_DiagMatMul_fu_589_A_M_real_ce0;
    end else begin
        rxmat_M_real_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_0_ce1 = grp_DiagMatMul_fu_589_A_M_real_ce1;
    end else begin
        rxmat_M_real_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln49_1_fu_691_p4 == 3'd0) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_real_0_we0 = 1'b1;
    end else begin
        rxmat_M_real_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rxmat_M_real_1_address0 = zext_ln49_fu_713_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_1_address0 = grp_DiagMatMul_fu_589_A_M_real1_address0;
    end else begin
        rxmat_M_real_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_real_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_1_ce0 = grp_DiagMatMul_fu_589_A_M_real1_ce0;
    end else begin
        rxmat_M_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_1_ce1 = grp_DiagMatMul_fu_589_A_M_real1_ce1;
    end else begin
        rxmat_M_real_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln49_1_fu_691_p4 == 3'd1) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_real_1_we0 = 1'b1;
    end else begin
        rxmat_M_real_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rxmat_M_real_2_address0 = zext_ln49_fu_713_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_2_address0 = grp_DiagMatMul_fu_589_A_M_real2_address0;
    end else begin
        rxmat_M_real_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_real_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_2_ce0 = grp_DiagMatMul_fu_589_A_M_real2_ce0;
    end else begin
        rxmat_M_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_2_ce1 = grp_DiagMatMul_fu_589_A_M_real2_ce1;
    end else begin
        rxmat_M_real_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln49_1_fu_691_p4 == 3'd2) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_real_2_we0 = 1'b1;
    end else begin
        rxmat_M_real_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        rxmat_M_real_3_address0 = zext_ln49_fu_713_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_3_address0 = grp_DiagMatMul_fu_589_A_M_real3_address0;
    end else begin
        rxmat_M_real_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_real_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_3_ce0 = grp_DiagMatMul_fu_589_A_M_real3_ce0;
    end else begin
        rxmat_M_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        rxmat_M_real_3_ce1 = grp_DiagMatMul_fu_589_A_M_real3_ce1;
    end else begin
        rxmat_M_real_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & ~(trunc_ln49_1_fu_691_p4 == 3'd0) & ~(trunc_ln49_1_fu_691_p4 == 3'd1) & ~(trunc_ln49_1_fu_691_p4 == 3'd2) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        rxmat_M_real_3_we0 = 1'b1;
    end else begin
        rxmat_M_real_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        xmat_M_imag_0_address0 = zext_ln60_1_fu_804_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_0_address0 = grp_DiagMatMul_fu_589_B_M_imag_0_address0;
    end else begin
        xmat_M_imag_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_imag_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_0_ce0 = grp_DiagMatMul_fu_589_B_M_imag_0_ce0;
    end else begin
        xmat_M_imag_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_0_ce1 = grp_DiagMatMul_fu_589_B_M_imag_0_ce1;
    end else begin
        xmat_M_imag_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln60_reg_963 == 2'd0) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_imag_0_we0 = 1'b1;
    end else begin
        xmat_M_imag_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        xmat_M_imag_1_address0 = zext_ln60_1_fu_804_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_1_address0 = grp_DiagMatMul_fu_589_B_M_imag_1_address0;
    end else begin
        xmat_M_imag_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_imag_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_1_ce0 = grp_DiagMatMul_fu_589_B_M_imag_1_ce0;
    end else begin
        xmat_M_imag_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_1_ce1 = grp_DiagMatMul_fu_589_B_M_imag_1_ce1;
    end else begin
        xmat_M_imag_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln60_reg_963 == 2'd1) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_imag_1_we0 = 1'b1;
    end else begin
        xmat_M_imag_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        xmat_M_imag_2_address0 = zext_ln60_1_fu_804_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_2_address0 = grp_DiagMatMul_fu_589_B_M_imag_2_address0;
    end else begin
        xmat_M_imag_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_imag_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_2_ce0 = grp_DiagMatMul_fu_589_B_M_imag_2_ce0;
    end else begin
        xmat_M_imag_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_2_ce1 = grp_DiagMatMul_fu_589_B_M_imag_2_ce1;
    end else begin
        xmat_M_imag_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln60_reg_963 == 2'd2) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_imag_2_we0 = 1'b1;
    end else begin
        xmat_M_imag_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        xmat_M_imag_3_address0 = zext_ln60_1_fu_804_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_3_address0 = grp_DiagMatMul_fu_589_B_M_imag_3_address0;
    end else begin
        xmat_M_imag_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_imag_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_3_ce0 = grp_DiagMatMul_fu_589_B_M_imag_3_ce0;
    end else begin
        xmat_M_imag_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_imag_3_ce1 = grp_DiagMatMul_fu_589_B_M_imag_3_ce1;
    end else begin
        xmat_M_imag_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln60_reg_963 == 2'd3) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_imag_3_we0 = 1'b1;
    end else begin
        xmat_M_imag_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        xmat_M_real_0_address0 = zext_ln60_1_fu_804_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_0_address0 = grp_DiagMatMul_fu_589_B_M_real_0_address0;
    end else begin
        xmat_M_real_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_real_0_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_0_ce0 = grp_DiagMatMul_fu_589_B_M_real_0_ce0;
    end else begin
        xmat_M_real_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_0_ce1 = grp_DiagMatMul_fu_589_B_M_real_0_ce1;
    end else begin
        xmat_M_real_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln60_reg_963 == 2'd0) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_real_0_we0 = 1'b1;
    end else begin
        xmat_M_real_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        xmat_M_real_1_address0 = zext_ln60_1_fu_804_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_1_address0 = grp_DiagMatMul_fu_589_B_M_real_1_address0;
    end else begin
        xmat_M_real_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_real_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_1_ce0 = grp_DiagMatMul_fu_589_B_M_real_1_ce0;
    end else begin
        xmat_M_real_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_1_ce1 = grp_DiagMatMul_fu_589_B_M_real_1_ce1;
    end else begin
        xmat_M_real_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln60_reg_963 == 2'd1) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_real_1_we0 = 1'b1;
    end else begin
        xmat_M_real_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        xmat_M_real_2_address0 = zext_ln60_1_fu_804_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_2_address0 = grp_DiagMatMul_fu_589_B_M_real_2_address0;
    end else begin
        xmat_M_real_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_real_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_2_ce0 = grp_DiagMatMul_fu_589_B_M_real_2_ce0;
    end else begin
        xmat_M_real_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_2_ce1 = grp_DiagMatMul_fu_589_B_M_real_2_ce1;
    end else begin
        xmat_M_real_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln60_reg_963 == 2'd2) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_real_2_we0 = 1'b1;
    end else begin
        xmat_M_real_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        xmat_M_real_3_address0 = zext_ln60_1_fu_804_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_3_address0 = grp_DiagMatMul_fu_589_B_M_real_3_address0;
    end else begin
        xmat_M_real_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_real_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_3_ce0 = grp_DiagMatMul_fu_589_B_M_real_3_ce0;
    end else begin
        xmat_M_real_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        xmat_M_real_3_ce1 = grp_DiagMatMul_fu_589_B_M_real_3_ce1;
    end else begin
        xmat_M_real_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (trunc_ln60_reg_963 == 2'd3) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        xmat_M_real_3_we0 = 1'b1;
    end else begin
        xmat_M_real_3_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln36_fu_661_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln45_fu_667_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln46_fu_679_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln46_fu_679_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln56_fu_745_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state6 : begin
            if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln57_fu_783_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else if ((~((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0)) & (icmp_ln57_fu_783_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((grp_DiagMatMul_fu_589_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln71_fu_836_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln71_fu_836_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((regslice_both_out_stream_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln36_fu_655_p2 = (phi_ln36_reg_522 + 8'd1);

assign add_ln60_fu_799_p2 = (zext_ln60_fu_795_p1 + zext_ln57_reg_967);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((1'b1 == ap_block_state10_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((1'b1 == ap_block_state10_io) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b1 == ap_block_state9_io) & (ap_enable_reg_pp0_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state10_io = ((icmp_ln71_reg_980_pp0_iter1_reg == 1'd0) & (out_stream_TREADY_int == 1'b0));
end

assign ap_block_state10_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4 = ((icmp_ln46_fu_679_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0));
end

always @ (*) begin
    ap_block_state6 = ((icmp_ln57_fu_783_p2 == 1'd0) & (in_stream_TVALID_int == 1'b0));
end

assign ap_block_state8_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state9_io = ((icmp_ln71_reg_980 == 1'd0) & (out_stream_TREADY_int == 1'b0));
end

assign ap_block_state9_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln49_fu_725_p1 = grp_fu_645_p4;

assign bitcast_ln52_fu_737_p1 = trunc_ln681_fu_733_p1;

assign bitcast_ln60_fu_816_p1 = grp_fu_645_p4;

assign bitcast_ln63_fu_828_p1 = trunc_ln681_1_fu_824_p1;

assign bitcast_ln74_fu_897_p1 = tmp_3_fu_883_p6;

assign bitcast_ln77_fu_915_p1 = tmp_4_fu_901_p6;

assign grp_DiagMatMul_fu_589_ap_start = grp_DiagMatMul_fu_589_ap_start_reg;

assign grp_fu_645_p4 = {{in_stream_TDATA_int[63:32]}};

assign i_3_fu_842_p2 = (i_2_reg_578 + 9'd1);

assign i_4_fu_751_p2 = (i_1_reg_556 + 7'd1);

assign i_fu_673_p2 = (i_0_reg_533 + 9'd1);

assign icmp_ln36_fu_661_p2 = ((phi_ln36_reg_522 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_667_p2 = ((i_0_reg_533 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_679_p2 = ((j_0_reg_545 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln56_fu_745_p2 = ((i_1_reg_556 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_783_p2 = ((j_1_reg_567 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln71_fu_836_p2 = ((i_2_reg_578 == 9'd256) ? 1'b1 : 1'b0);

assign j_2_fu_789_p2 = (j_1_reg_567 + 9'd1);

assign j_fu_685_p2 = (j_0_reg_545 + 7'd1);

assign lshr_ln_fu_761_p4 = {{i_1_reg_556[6:2]}};

assign out_stream_TDATA_int = {{bitcast_ln74_fu_897_p1}, {bitcast_ln77_fu_915_p1}};

assign out_stream_TVALID = regslice_both_out_stream_V_data_V_U_vld_out;

assign tmp_6_fu_771_p3 = {{lshr_ln_fu_761_p4}, {8'd0}};

assign tmp_7_fu_705_p3 = {{i_0_reg_533}, {trunc_ln49_fu_701_p1}};

assign trunc_ln1079_fu_858_p1 = i_2_reg_578[5:0];

assign trunc_ln49_1_fu_691_p4 = {{j_0_reg_545[6:4]}};

assign trunc_ln49_fu_701_p1 = j_0_reg_545[3:0];

assign trunc_ln60_fu_757_p1 = i_1_reg_556[1:0];

assign trunc_ln681_1_fu_824_p1 = in_stream_TDATA_int[31:0];

assign trunc_ln681_fu_733_p1 = in_stream_TDATA_int[31:0];

assign valOut_last_V_fu_874_p2 = ((i_2_reg_578 == 9'd255) ? 1'b1 : 1'b0);

assign zext_ln1079_1_fu_880_p1 = lshr_ln1_reg_989;

assign zext_ln1079_fu_862_p1 = trunc_ln1079_fu_858_p1;

assign zext_ln49_fu_713_p1 = tmp_7_fu_705_p3;

assign zext_ln57_fu_779_p1 = tmp_6_fu_771_p3;

assign zext_ln60_1_fu_804_p1 = add_ln60_fu_799_p2;

assign zext_ln60_fu_795_p1 = j_1_reg_567;

always @ (posedge ap_clk) begin
    zext_ln57_reg_967[7:0] <= 8'b00000000;
    zext_ln57_reg_967[13] <= 1'b0;
end

endmodule //matmul
